### ISSUE TITLE
can't create project Ionic with vue or React

### ISSUE THREAD

**Issue by bobwatcherx** [ionic-team/ionic-cli#4791] opened 2021-12-11 13:46 UTC
**# ionic start ionvu tabs --type vue**
✔ Preparing directory ./ionvu in 5.02ms
✔ Downloading and extracting tabs starter in 2.84s
> ionic integrations enable capacitor --quiet -- ionvu io.ionic.starter
> npm i --save -E @capacitor/core@latest
Error

at new SubprocessError (/usr/local/lib/node_modules/@ionic/cli/node_modules/@ionic/utils-subprocess/dist/index.js:41:23)
at ChildProcess.<anonymous>
(/usr/local/lib/node_modules/@ionic/cli/node_modules/@ionic/utils-subprocess/dist/index.js:125:27)
at ChildProcess.emit (node:events:369:20)
at maybeClose (node:internal/child_process:1067:16)
at Socket.<anonymous> (node:internal/child_process:453:11)
at Socket.emit (node:events:369:20)
at Pipe.<anonymous> (node:net:666:12)

**node version**
v15.14.0

**npm version**
7.7.6
**ionic info**
Ionic:

   Ionic CLI : 6.18.1

Utility:

   cordova-res : 0.15.4
   native-run  : not installed globally

System:

   NodeJS : v15.14.0
   npm    : 7.7.6
   OS     : Linux 5.14

**Comment by jcesarmobile** [comment] 2022-05-06 14:16
I can't reproduce now, it was probably some peer dependency problem on the starters that caused problems on npm 7, but should be fixed now.

**Closed as completed by jcesarmobile** 2022-05-06 14:16 UTC
Labels: triage
