### ISSUE TITLE
ionic serve disconnected in some times

### ISSUE THREAD

**Issue by immohdali** [ionic-team/ionic-cli#2464] opened 2017-06-22 10:45 UTC
D:\tutorials\ionic2\myapp>ionic serve
[INFO] Starting app-scripts server: --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address 0.0.0.0 - Ctrl+C to  cancel

[16:14:35]  watch started ...
[16:14:35]  build dev started ...
[16:14:35]  clean started ...
[16:14:35]  clean finished in 16 ms
[16:14:35]  copy started ...
[16:14:35]  transpile started ...
[16:14:43]  transpile finished in 8.54 s
[16:14:43]  preprocess started ...
[16:14:43]  deeplinks started ...
[16:14:43]  deeplinks finished in 16 ms
[16:14:43]  preprocess finished in 16 ms
[16:14:43]  webpack started ...
[16:14:45]  copy finished in 9.86 s
[16:14:59]  webpack finished in 15.55 s
[16:14:59]  sass started ...
[16:15:04]  sass finished in 4.79 s
[16:15:04]  postprocess started ...
[16:15:04]  postprocess finished in 104 ms
[16:15:04]  lint started ...
[16:15:04]  build dev finished in 29.21 s
[16:15:04]  watch ready in 29.82 s
[16:15:04]  dev server running: http://localhost:8100/

[INFO] Development server running
       Local: http://localhost:8100

[16:15:20]  lint finished in 16.53 s

D:\tutorials\ionic2\myapp\node_modules\tiny-lr\src\server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
    at Server.error (D:\tutorials\ionic2\myapp\node_modules\tiny-lr\src\server.js:266:52)
    at Socket.<anonymous> (D:\tutorials\ionic2\myapp\node_modules\tiny-lr\src\server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:467:13)
    at Socket._destroy (net.js:508:3)
    at Socket._writeGeneric (net.js:711:17)

**Comment by janpio** [comment] 2017-06-22 11:47
What is your `ionic info` output?

**Comment by immohdali** [comment] 2017-06-22 12:07
D:\tutorials\ionic2\firstapp>ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.3


D:\tutorials\ionic2\firstapp>cordova --v
7.0.1

**Comment by rogeraleite** [comment] 2017-06-27 14:17
Same issue here.

global packages:

    @ionic/cli-utils : 1.4.0
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.1.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Ionic Framework                 : ionic-angular 2.0.1

System:

    Node       : v7.9.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.0.1

**Comment by dwieeb** [comment] 2017-07-10 21:33
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2479

**Closed by dwieeb** 2017-07-10 21:33 UTC
