### ISSUE TITLE
Custom Fonts not showing in ionic-cli@3.9.2

### ISSUE THREAD

**Issue by JaneDawson** [ionic-team/ionic-cli#2675] opened 2017-08-19 16:53 UTC
**Description:**
After an update to version 3.9.2 my custom font is not shown anymore (at least on iOS). It is replaced by a standard font.

Rolling back to 3.8.1 makes everything working fine again. 

**Steps to Reproduce:**
add the following to app.scss & add the *.ttf file to `src/assets/fonts `
```
@font-face {
    font-family: "custom-font";
    src: url(../assets/fonts/your-font-here.ttf) format("truetype");
}

.custom-style{
    font-family: "custom-font"!important;
}
```
Add this style to a div.

**My `ionic info`:**
```
cli packages: 

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    ios-deploy : 1.9.1 
    Node       : v8.3.0
    npm        : 5.3.0 
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 


```

**Comment by cingolanifede** [comment] 2017-08-20 03:29
I am having the same problem.
My ionic info:
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.3.0

System:

    Node : v6.10.1
    npm  : 5.3.0
    OS   : Windows 10

**Comment by amjadyahya** [comment] 2017-08-20 07:30
Same on Android

**Comment by betatools** [comment] 2017-08-20 11:24
I have same issue. Downgraded to 3.9.1 made it work again

cli packages: (/Users/jakob/Code/hypnose/barn/app v2/node_modules)

    @ionic/cli-utils  : 1.9.1
    ionic (Ionic CLI) : 3.9.1

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1
    ios-sim           : 6.0.0
    Node              : v6.11.0
    npm               : 3.10.10
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b

**Comment by masandraki** [comment] 2017-08-20 15:34
Solution: Move custom fonts (I use ttf format) 
from /assets/fonts 
to /assets 
folder and update paths in scss file: 

`@font-face { 
font-family: YourFont; 
src: url("…/assets/YourFont.ttf"); 
} `

It works for me on IOS and Android with Ionic CLI 3.9.2

**Comment by amjadyahya** [comment] 2017-08-21 10:09
Not only the custom fonts, but also all default ionic fonts e.i. roboto font family.

**Comment by pfurini** [comment] 2017-08-22 13:43
> Not only the custom fonts, but also all default ionic fonts e.i. roboto font family.

Same for me, very annoying.. rolling back to 3.9.1 resolved the issue

**Comment by Remco75** [comment] 2017-08-23 13:59
Same here, this is really a bug. For now I will move my stuff to a different directory. But this is really starting to piss me off (excuse my language) EVERY update that is pushed will have me starting to fear what I will encounter on the first run. I NEVER works out of the box.
</end-rant>

**Comment by isaiasas** [comment] 2017-08-23 17:58
Same issue here. Ionic default fonts can't be found on Android under 3.9.2

**Comment by BugHunter2k** [comment] 2017-08-24 09:48
Same here

**Comment by gino8080** [comment] 2017-08-24 15:23
same

**Comment by akshaydwivedi29** [comment] 2017-08-25 07:09
the problem seems to be the ionic-scripts/webpack ignoring  TTF files. I tried **USING WOFF**  or WOFF2 format and everything works fine.

**Comment by Remco75** [comment] 2017-08-25 07:56
pfff don't these guys have unit / regression tests for this kind of stuff....

**Comment by Madm0x** [comment] 2017-08-25 16:27
+1

**Comment by shajeeck** [comment] 2017-08-25 23:06
every asset file stopped loaded when using relative paths in `index.html` with `src, href = '../assets/folder/etc'` on devices using `ionic cordova run`

changing to `'assets/folder/etc'` works, but  now default fonts are not loading!

**Comment by stalinkay** [comment] 2017-08-28 22:40
+1

**Comment by janpio** [comment] 2017-08-31 16:23
> pfff don't these guys have unit / regression tests for this kind of stuff....

As everything is open source you can check that yourself and also submit a PR to fix any missing tests so this doesn't happen in the future.

**Comment by Remco75** [comment] 2017-08-31 16:58
@janpio True, I will look into that. But open-source or not, I expect from a piece of software created by a business a certain standard, and I was surprised about the amount of bugs after each release.
But I will try to be more constructive (and will try to find a solution for this)

**Comment by betatools** [comment] 2017-09-03 11:40
@jgw96 Any news on this issue?

Thx in advance

**Comment by danbucholtz** [comment] 2017-09-06 18:55
Hi all, we'll fix this now. Sorry, we have been very busy with some big internal changes to the Ionic project. Expect this to land in the next few days.

Thanks,
Dan

**Comment by sidthesloth92** [comment] 2017-09-06 20:56
Fix will be welcome.

**Comment by danbucholtz** [comment] 2017-09-06 21:37
Everyone,

I dove into this issue this afternoon and have cracked the case 🕵️ .

So here's what's going on:

This code has existed for a really long time but we did not start setting the `platform` and `target` since recently. This change was part of our move towards eventual support of a PWA target.

The code became active one the `target` and `platform` were set. The code has always looked at the `www/assets/fonts` directory to purge ionic specific fonts that aren't needed on a given platform. We did this due to complaints about unnecessary bytes in `.apk` and `.ipa` files (iOS and Android application binaries). We do the same thing with source maps on prod builds.

Our code was never smart to distinguish between ionic provided fonts and user fonts. Now that we know people are re-using the `www/assets/fonts` directory, we will update the code to be smart and ONLY remove ionic provided fonts.

I'll have a nightly available soon, and we'll release this properly next week.

Thanks,
Dan

**Comment by danbucholtz** [comment] 2017-09-07 05:05
In theory, this issue should be fixed in this [commit](https://github.com/ionic-team/ionic-app-scripts/commit/0dd1b223d1cfdbef97b5a61d5e936bff7f32eda3).

Can you please validate for me and let me know if things are working better?

```
npm install @ionic/app-scripts@nightly
```

If everything is all good, we'll release this version early next week.

Thanks,
Dan

**Closed by danbucholtz** 2017-09-07 05:05 UTC

**Comment by gmarab** [comment] 2017-09-11 15:20
Hi @danbucholtz, it's work!
Ionic CLI 3.9.2 and the @ionic/app-scripts@nightly.

**Comment by aks0020** [comment] 2017-09-18 06:52
@danbucholtz tested today for me it only works if I downgrade to `ionic 3.9.1` does not work with `ionic 3.9.2` or latest `3.10.3` even with latest `@ionic/app-scripts - ^2.1.4-201709131805`, inbuilt roboto fonts are not loaded only checked with `--prod` build for Android. also if I use latest nightly app-scripts with old `3.9.1` cli version it still works so this might be issue with cli & not app-scripts.
<img width="927" alt="font-err-android" src="https://user-images.githubusercontent.com/2557058/30531412-cc88258a-9c6b-11e7-96da-642bb4cc88c3.png">

**Comment by aks0020** [comment] 2017-09-18 07:06
installing nightly app scripts again fixed issue somehow don't know what happened before so removing above comment.

**Comment by mebibou** [comment] 2017-09-20 08:16
I don't think this is fixed, I am using `3.10.3` and when running `ionic serve` the fonts are now loading correctly (and they appear under `./www/assets/fonts` folder), but when then running `ionic cordova run android` the fonts are not present under `./platforms/android/assets/www/fonts` and they actually get removed from the `./www/assets/fonts` folder.

I had to downgrade again to `3.9.1` and it worked straight away

**Comment by mebibou** [comment] 2017-09-20 08:28
The steps I did:
1. I was on `3.9.1`, everything worked
2. `npm install ionic@3.10.3 --save-exact`
3. `ionic serve` => the fonts are present in `www/assets/fonts` folder
4. `ionic cordova build android`

=> only `ionicons.woff` and `ionicons.woff2` in `www/assets/fonts` folder, same for `platforms/android/assets/www/fonts`

**Comment by mebibou** [comment] 2017-09-20 08:35
Oh no ok got it, this issue talks about loading custom fonts, not the default Roboto font like #2707. So ignore my comments

**Comment by scarings** [comment] 2017-09-22 07:33
hey @danbucholtz, after installing `@ionic/app-scripts@nightly`, i got error message `TypeError: Cannot read property 'exports' of undefined`

> cli packages:

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.1.4-201709211652
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.3.0

System:

    ios-deploy : 1.9.1
    Node       : v6.10.3
    npm        : 3.10.10
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b

**Comment by scarings** [comment] 2017-09-22 07:41
ignore my comments, after convert font from `.ttf to woff`, and installing latest `app-script`,its work now..

**Comment by Barathwaja** [comment] 2017-09-23 16:44
@scarings so is **3.10.3 good**?? but have to install nightly version of **app-scripts**?

**Comment by delian7** [comment] 2017-09-23 22:06
3.12.0 ionic cli is still experiencing this problem when running `ionic cordova build ios`. All of my fonts are being removed. (see screenshot). 

`ionic info`: 

```
cli packages: (/Users/delian/seastatus/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : ios 4.5.0
    Ionic Framework    : ionic-angular 3.6.1

System:

    ios-sim : 6.1.2 
    Node    : v8.4.0
    npm     : 5.2.0 
    OS      : macOS Sierra
    Xcode   : Xcode 9.0 Build version 9A235 

Misc:

    backend : legacy
```

**Comment by Barathwaja** [comment] 2017-09-24 03:04
Yes yes @delian7 3.12 is also experiencing same.. I have downgraded to 3.9.1 as of now.. that's the stable one I think.

**Comment by nabinkumarn** [comment] 2017-09-24 06:14
Yes 3.9.1 is only the latest one that does not have this issue. Other all later versions delete custom fonts and built in fonts i.e. roboto fonts on running cordova build android. I check each time new version arrives to see if the issue is fixed and get disappointed. Hope it is fixed soon.

**Comment by delian7** [comment] 2017-09-24 06:26
thanks for confirming. Hmm, wonder why this issue is closed? @danbucholtz should I make another issue with the current version number (3.12)?

**Comment by Barathwaja** [comment] 2017-09-24 13:34
Try raising again let's see.. I have opened one in ionic-appscripts..

**Comment by hervethouzard** [comment] 2017-09-25 14:50
Problem still exists with ionic cli 3.12.0 (under Windows)

**Comment by danbucholtz** [comment] 2017-09-25 18:08
This will ship on Wednesday. Sorry for the delay.

Thanks,
Dan

**Comment by hervethouzard** [comment] 2017-09-25 19:52
no problem, thank you very much

**Comment by FanFanFantastic** [comment] 2017-09-27 21:13
any updates now?, I did ionic build browser -prod and now my web page on the serve is complaining about the fonts

**Comment by dwieeb** [comment] 2017-09-28 23:11
`@ionic/app-scripts` 3.0.0 is out. Please update w/ `npm i @ionic/app-scripts@latest`

**Comment by hervethouzard** [comment] 2017-09-29 07:21
Hello,

In my case the problem seems to be solved.
Thank you very much.

**Comment by aks0020** [comment] 2017-09-29 08:21
@dwieeb It still does not load(with app-scripts `3.0.0` & cli `3.12.0`) default roboto fonts on android prod build
If I run `ionic cordova build android` it copies all fonts in the `android/assets/www/assets` but if I run it with `--prod` flags it removes all fonts except `ionicons` & in android dev tools it show many errors for roboto fonts not found. (I have not added any custom fonts & it works fine with `cli 3.9.1`)

<img width="218" alt="android-font-issue" src="https://user-images.githubusercontent.com/2557058/31007152-272f607a-a51d-11e7-9c97-c0e29c55cfc9.png">

**Comment by aks0020** [comment] 2017-09-29 08:34
@dwieeb I have checked code in [this](https://github.com/ionic-team/ionic-app-scripts/blob/24cb5caceac2ff010620b94594fe0f37eb317bdd/src/optimization/remove-unused-fonts.ts) line 46 & as per code roboto font is not needed for android & it is removing it then I should not get console errors for it

<img width="927" alt="font-err-android" src="https://user-images.githubusercontent.com/2557058/31007698-03fae802-a51f-11e7-9822-26ad6475d20f.png">

**Comment by mebibou** [comment] 2017-09-29 09:01
@dwieeb @aks0020 there is some confusion on those 2 different issues:
- loading custom font put in `src/assets/fonts` folder
- loading the default `Roboto` font on Android

This issue here talks about the first one, that I think was fixed successfully on latest `ionic-cli` version.
The second one is explained [here](https://github.com/ionic-team/ionic-cli/issues/2707) and now works without the `--prod` flag

**Comment by aks0020** [comment] 2017-09-29 09:07
@mebibou but it should work with `--prod` flag so 2nd roboto issue is not fixed yet. & as per current code of app-script it is intentionally removing roboto font from android prod build so if its not needed for android it should not show error & if it is needed then code needs to be fixed.

**Comment by mebibou** [comment] 2017-09-29 09:15
@aks0020 yes I agree but please move your comments to the correct issue is all i'm saying

**Comment by aks0020** [comment] 2017-09-29 09:18
@dwieeb Also if if I am understanding this code correctly
```javascript
if (platform === 'android') {
      // remove noto-sans, roboto, and non-woff ionicons
      if (fileName.startsWith('noto-sans') || fileName.startsWith('roboto') || (isIonicons(fileName) && !isWoof(fileName))) {
        filesToDelete.add(fileName);
      }
    } else if (platform === 'ios') {
      // remove noto-sans, non-woff ionicons
      if (fileName.startsWith('noto-sans') || (fileName.startsWith('roboto') && !isWoof(fileName)) || (isIonicons(fileName) && !isWoof(fileName))) {
        filesToDelete.add(fileName);
      }
    }
```
is it possible to use custom font whose name starts with `roboto` or `nato` (suppose if someone wants to use nato-sans in iOS then it will remove it automatically) if not custom font issue is also not fixed .

**Comment by aks0020** [comment] 2017-10-02 11:43
after updating to ionic-angular 3.7.1 android roboto fonts errors with --prod are not showing for me so that issue is fixed for me.

**Comment by fbrun** [comment] 2017-10-16 14:57
I use  ionic-angular 3.7.1 and cordova-android 6.2.3. cli version 3.13.0
When i make a ionic cordova build android --prod --debug, i have the error : only my own css and ionicons are presents in assets/fonts (www and platforms android).

My ionic info
`cli packages: (/.../.nvm/versions/node/v6.11.0/lib/node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.0.1 
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    Node              : v6.11.0
    npm               : 4.6.1 
    OS                : Linux 4.4
`

**Comment by JaneDawson** [comment] 2017-10-16 15:52
I'm experiencing a similar issue. Custom fonts are working now. However, now there are problems with the css files of plugins (like [ionic2-super-tabs](https://github.com/zyra/ionic2-super-tabs)) that are not available when building with` --prod`.

Building with `ionic cordova run android --aot --minifyjs --minifycss --optimizejs` instead seems to work.

**Comment by SquallX** [comment] 2017-10-20 14:30
Still does not work on android, the roboto font does not load.

`cli packages: (/Users/alexandre/Sites/app-mobiles/LeRugbynistere/LeRugbynistere/node_modules)

    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 5.0.13 
    Node              : v7.5.0
    npm               : 5.4.2 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.0 Build version 9A235 

Misc:

    backend : pro
`

**Comment by janpio** [comment] 2017-10-20 15:16
Github issues is not the right place for problems and questions. Post at https://forum.ionicframework.com/

**Comment by Remco75** [comment] 2017-10-20 15:29
@janpio does that mean that this is not considered an issue at this point?

**Comment by JaneDawson** [comment] 2017-10-20 15:35
I think it still is an issue. Roboto is not working for me either, when building with --prod flag.

**Comment by janpio** [comment] 2017-10-20 15:55
Then create an issue about Roboto not loading. This an already closed issue is about custom fonts. No one will look at it and reopen it for a different problem.

**Comment by deepakrout** [comment] 2017-10-21 16:39
I still see this is an issue. I am using ionic (Ionic CLI) : 3.13.1 and  @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.3.1
    Ionic Framework    : ionic-angular 3.7.1

Please let me know if anyone has any update on this.

**Comment by Remco75** [comment] 2017-10-21 18:23
@janpio  Im sorry, but this really weird.... there are at least 10 user above here claiming the issue persist, and the only contributer commenting nags about a small detail about a side effect.come on.

But I will just a myself to the line then:
This is not resolved, still happening with me as well: ionic cli 3.13.1, same behaviour as @deepakrout

**Comment by deepakrout** [comment] 2017-10-21 21:45
I tried with @ionic/app-scrips@3.0.1, didn't seem resolve the issue. @Remco75  Which version worked for you?

**Comment by JaneDawson** [comment] 2017-10-23 16:14
I opened a new issue for roboto fonts not loading:
https://github.com/ionic-team/ionic-cli/issues/2822

**Comment by DuaneQ** [comment] 2018-02-19 02:00
@danbucholtz  running npm install ionic@3.9.1 should work did not work for me.  I'm still getting the following:
Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor.js:135679 Ionic Native: deviceready event fired after 2794 ms
roboto-regular.woff Failed to load resource: net::ERR_FILE_NOT_FOUND
roboto-medium.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
roboto-medium.woff Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by ravi-pandit14** [comment] 2018-03-23 06:30
@akshaydwivedi29  in production build it throw the error in ionic 2

**Comment by akshaydwivedi29** [comment] 2018-03-24 17:19
@ravi-pandit14 what kind of error you're facing in prod build? coz, for me, it works when I switched to woff or woff2 versions of the same fonts.

**Comment by Heena-Vora** [comment] 2018-04-07 09:38
even not till now working

```
cli packages: (C:\Users\UserXx\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.0
    npm               : 5.8.0
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\Users\UserXx\android-sdks

Misc:

    backend : pro
```

**Comment by dwieeb** [comment] 2018-05-24 20:00
Does this workaround not work? https://github.com/ionic-team/ionic-cli/issues/2822#issuecomment-340078265

**Comment by douglasjam** [comment] 2018-08-29 07:33
Still not working as intended.
It just works if I have my fonts in assets instead of assets/fonts

Looking for a fix

**Comment by nabinkumarn** [comment] 2018-08-29 07:37
`"config": {
    "ionic_purge_unused_fonts": false
  },`
adding this to package.json fixes for now.

**Comment by brodriguezs** [comment] 2018-10-25 16:44
The worst part is that for me the only way that I found was, to create a new ionic project template blank (not Ionic 4), and migrate all my app to that (part by part), finally that works, with the latest app-scripts version 3.1.7. That was a long way =/ but it finally works for me.

**Comment by bunday** [comment] 2018-11-20 12:22
There is an easy workaround which I'm going to show you, for the sake of this, I will be using the Font Family "Lato"

1. Move your fonts into a folder in the `src\assets` folder 
2. Go into your variable.scss and add the following code 
` @font-face { font-family: Lato; src: url("../assets/fonts/Lato-Regular.ttf"); }`
The source here is the part to the font you've slated in 1 above
3. Next specify the Font Family name for web, android, ios and windows
For Web and Android: `$font-family-md-base: "Lato";`
For iOS: `$font-family-ios-base: "Lato";`
For Windows Phone: `$font-family-wp-base: "Lato"; `

4. Save and try it out!

**Comment by ravi-pandit14** [comment] 2018-11-21 04:45
Thank you

**Comment by Pratikshakhandagale** [comment] 2019-08-01 09:32
Thanks @bunday this solution work for me.
