### ISSUE TITLE
Ionic npm install failing

### ISSUE THREAD

**Issue by steven-ponessa** [ionic-team/ionic-cli#3747] opened 2018-11-15 03:14 UTC
**Description:**

**Steps to Reproduce:**
npm install -g cordova ionic

**Output:**
npm ERR! 404 Not Found: @ionic/cli-framework@1.3.0

```
89 verbose stack Error: 404 Not Found: @ionic/cli-framework@1.3.0
89 verbose stack     at fetch.then.res (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
89 verbose stack     at tryCatcher (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
89 verbose stack     at Promise._settlePromiseFromHandler (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
89 verbose stack     at Promise._settlePromise (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
89 verbose stack     at Promise._settlePromise0 (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
89 verbose stack     at Promise._settlePromises (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
89 verbose stack     at Async._drainQueue (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
89 verbose stack     at Async._drainQueues (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
89 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/steve/.nvm/versions/node/v9.5.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
89 verbose stack     at runCallback (timers.js:756:18)
89 verbose stack     at tryOnImmediate (timers.js:717:5)
89 verbose stack     at processImmediate [as _immediateCallback] (timers.js:697:5)
90 verbose cwd /Users/steve/$toLearn/ionic
91 verbose Darwin 17.7.0
92 verbose argv "/Users/steve/.nvm/versions/node/v9.5.0/bin/node" "/Users/steve/.nvm/versions/node/v9.5.0/bin/npm" "install" "-g" "cordova" "ionic"
93 verbose node v9.5.0
94 verbose npm  v6.4.0
95 error code E404
96 error 404 Not Found: @ionic/cli-framework@1.3.0
97 verbose exit [ 1, true ]


```

**My `ionic info`:**

```
N/A
```

**Other Information:**

**Comment by dwieeb** [comment] 2018-11-15 17:13
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3656

**Closed by dwieeb** 2018-11-15 17:13 UTC
Labels: triage
