### ISSUE TITLE
ionic cordova run livereload does not show the logs

### ISSUE THREAD

**Issue by GuilhermeBCC** [ionic-team/ionic-cli#3346] opened 2018-07-03 17:58 UTC
**Description:**
I'm using IONIC 4. When I run the command "ionic cordova run android --device -lc" the logs (console.log) on the terminal are not shown.

I'm worried because the consoles are vital to my tests.

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.0-rc.9
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
   @angular-devkit/core       : 0.7.0-rc.0
   @angular-devkit/schematics : 0.7.0-rc.0
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0-rc.9
   @ionic/schematics-angular  : 1.0.0-rc.9

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.0.1
   OS                : Windows 10
```

**Other Information:**

**Comment by dwieeb** [comment] 2018-07-03 18:58
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3169

**Closed by dwieeb** 2018-07-03 18:58 UTC
Labels: triage
