### ISSUE TITLE
Error: It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one.

### ISSUE THREAD

**Issue by zindelluib** [ionic-team/ionic-cli#2687] opened 2017-08-22 06:03 UTC
I ran **ionic serve -b**.  If i dont have any network connectivity this error message happens:

> **Error: It appears that you do not have any external network interfaces. In order to use livereload with emulate you will need one.**

But if I am connected to wifi or any network connection, the server runs
This is my Ionic Environment Info

cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.0
    npm  : 3.10.10 
    OS   : Linux 4.10

**Comment by hermitdemschoenenleben** [comment] 2017-08-29 06:48
I have the same problem while not connected to a network

**Comment by dwieeb** [comment] 2017-08-29 22:00
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2690

**Closed by dwieeb** 2017-08-29 22:00 UTC

**Comment by Kanyango** [comment] 2017-09-03 14:06
$ ionic serve  --address 127.0.0.1 -p 8800
specify a port of your choice i.e -p 8100
This worked for me

**Comment by BabyManisha** [comment] 2022-05-12 11:50
`npx cap sync` worked for me
