### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near      '...^5.0.1"},"_hasShrinkw'

### ISSUE THREAD

**Issue by NodeDevs** [ionic-team/ionic-cli#3321] opened 2018-06-22 03:32 UTC
ionic start newproject blank
✔ Creating directory ./newproject - done!
✔ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS and Andro
id? Yes
✔ Personalizing ionic.config.json and package.json - done!
> ionic integrations enable cordova --quiet
✔ Downloading integration cordova - done!
✔ Copying integrations files to project - done!
[OK] Added cordova integration!

Installing dependencies may take several minutes.

  ✨   IONIC  DEVAPP  ✨

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -  🔑
  -  🚀

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
✖ Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        
        npm ERR! Unexpected end of JSON input while parsing near 
        '...^5.0.1"},"_hasShrinkw'
        
        npm ERR! A complete log of this run can be found in:
        npm ERR!     /home/geek/.npm/_logs/2018-06-22T02_52_15_760Z-debug.log

**Comment by NodeDevs** [comment] 2018-06-22 03:35
It was working before but after updating npm to version 5.6.0 from the previous version, the problem started. i have tried  to uninstall npm and reinstall again but hasnt worked so far. please help

**Comment by dwieeb** [comment] 2018-06-22 15:49
Likely duplicate of https://github.com/ionic-team/ionic-cli/issues/3298

**Comment by dwieeb** [comment] 2018-06-22 15:50
Basically, try installing Node 8 and then updating to the latest npm@5:

```
npm install -g npm@5
```

**Comment by Elvis254** [comment] 2018-06-26 16:57
Check the last comment under this issue #3298 I found out a way of solving JSON parsing issue on Windows PC.

**Closed** 2018-06-26 22:08 UTC
