### ISSUE TITLE
Use the host loopback address when using the live reload feature on Android emulators.

### ISSUE THREAD

**Issue by carlpoole** [ionic-team/ionic-cli#4419] opened 2020-05-04 21:51 UTC
Currently when using live reload to use with the Android Emulator it tries to hit localhost by default which is the emulator itself. This results in an error in the web view in the app. 

Android emulators can reach the local host machine by using 10.0.2.2 (see: https://developer.android.com/studio/run/emulator-networking.html).

**Comment by dwieeb** [comment] 2020-05-19 20:34
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4057

**Closed by dwieeb** 2020-05-19 20:34 UTC
Labels: capacitor, enhancement
