### ISSUE TITLE
Ionic serve was accidentally terminate

### ISSUE THREAD

**Issue by kenphanith** [ionic-team/ionic-cli#2028] opened 2017-03-24 07:22 UTC
I have the latest version of ionic installed on my system. when  I run "ionic serve" it seem to work properly but after few seconds later it show some error as following:

TypeError: Cannot read property 'message' of undefined
    at Server.error (D:\xxxxxxx\xxxxxxx\project\node_modules\tiny-lr\src\server.js:266:52)
    at Socket.<anonymous> (D:\xxxxxxxx\xxxxxxx\project\node_modules\tiny-lr\src\server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:483:13)
    at Socket._destroy (net.js:524:3)
    at Socket._writeGeneric (net.js:727:17)
    at Socket._write (net.js:746:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-hello-world@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livere
load-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ ionic:serve script 'ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--po
rt" "8100" "--livereload-port" "35729"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\phanith\AppData\Roaming\npm-cache\_logs\2017-03-24T06_52_49_748Z-debug.log

And this is the output of "ionic info":

Your system information:
Cordova CLI: 6.5.0
Ionic Frameowork Version: 2.3.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v7.7.4
Xcode version: Not installed

I was stuck with this since few days ago. Can anyone help me out with this problem? I cannot move on unless this problem solved. Thank you so much for your consideration.

**Comment by ramzauchenna** [comment] 2017-03-28 08:48
Me too. Having same issue with a new ionic app. It just stays at ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"

**Comment by kenphanith** [comment] 2017-03-29 17:36
Any comments or suggestions from ionic team are appreciated

**Comment by dwieeb** [comment] 2017-08-02 05:11
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2479

**Closed by dwieeb** 2017-08-02 05:11 UTC
