### ISSUE TITLE
ionic serve not working

### ISSUE THREAD

**Issue by gregduffield** [ionic-team/ionic-cli#2959] opened 2018-01-17 12:12 UTC
**Description:**
Running ionic serve does not start the hosting service and does not serve any pages. Running npm run ionic:serve does work but this does not allow you to connect using devapp etc.

**Steps to Reproduce:**
From a fresh install of Node, NPM and Ionic.
create a new ionic project using ionic start myApp tabs
cd myApp
run ionic serve

`PS C:\Users\g.duffield\myapp> ionic serve
Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --nobrowser -
Ctrl+C to cancel
[12:11:15]  watch started ...
[12:11:15]  build dev started ...
[12:11:15]  clean started ...
[12:11:15]  clean finished in 5 ms
[12:11:15]  copy started ...
[12:11:15]  deeplinks started ...
[12:11:15]  deeplinks finished in 17 ms
[12:11:15]  transpile started ...
[12:11:18]  transpile finished in 2.69 s
[12:11:18]  preprocess started ...
[12:11:18]  preprocess finished in 1 ms
[12:11:18]  webpack started ...
[12:11:18]  copy finished in 2.83 s
[12:11:23]  webpack finished in 4.67 s
[12:11:23]  sass started ...
Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[12:11:23]  sass finished in 885 ms
[12:11:23]  postprocess started ...
[12:11:23]  postprocess finished in 6 ms
[12:11:23]  lint started ...
[12:11:23]  build dev finished in 8.37 s
[12:11:24]  watch ready in 8.43 s
[12:11:24]  dev server running: http://localhost:8100/

[OK] Development server running!
     Local: http://localhost:8100
     External: http://172.27.161.1:8100, http://10.0.75.1:8100, http://192.168.3.92:8100
     DevApp: myapp@8100 on DESKTOP-F572B2I

PS C:\Users\g.duffield\myapp>`

ionic Info 
`PS C:\Users\g.duffield\myapp> ionic info

cli packages: (C:\Users\g.duffield\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

local packages:

    @ionic/app-scripts : 3.1.6
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : pro

PS C:\Users\g.duffield\myapp>`

This does not build confidence about the ability for this framework to be used in a commercial environment when the very first task/test does not work as described.

**Comment by dwieeb** [comment] 2018-01-17 19:51
@gregduffield Thanks for the issue report. We were looking into this in this issue: https://github.com/ionic-team/ionic-cli/issues/2879 If there's anything you can contribute to the discussion, it would be most helpful. I have not yet been able to replicate the issue on my Windows 10 machine.

Duplicate of https://github.com/ionic-team/ionic-cli/issues/2879

**Closed by dwieeb** 2018-01-17 19:51 UTC
