### ISSUE TITLE
ionic upload TypeError: Can't call method on undefined

### ISSUE THREAD

**Issue by misaacson** [ionic-team/ionic-cli#1543] opened 2016-10-14 16:05 UTC
#### Short description of the problem:

When running ionic upload I get the following error:

```
(node:40232) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/michael/Git/uwsearch/node_modules/core-js/modules/_defined.js:3:28)
    at createHTML (/Users/michael/Git/uwsearch/node_modules/core-js/modules/_string-html.js:7:19)
    at bold (/Users/michael/Git/uwsearch/node_modules/core-js/modules/es6.string.bold.js:5:12)
    at cb (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:206:7)
    at done (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:167:19)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:40:16
    at /usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:193:9
    at Console.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/transports/console.js:127:3)
    at emit (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:186:17)
    at /usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:157:13
    at _each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/local/lib/node_modules/ionic/node_modules/async/lib/async.js:156:9)
    at Logger.log (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/logger.js:214:9)
    at target.(anonymous function) [as info] (/usr/local/lib/node_modules/ionic/node_modules/winston/lib/winston/common.js:54:18)
    at Request._callback (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/upload.js:150:11)
```
#### What behavior are you expecting?

**Steps to reproduce:**
1. Navigate to project folder
2. run `ionic upload`

*\* Output of `ionic info`**

```
Cordova CLI: 6.2.0
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: Not installed
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v6.2.2
Xcode version: Xcode 8.0 Build version 8A218a
```

**Comment by misaacson** [comment] 2016-10-14 17:27
This is a Node version issue. Downgrading to 5.12 resolved this issue.

**Comment by jkrot** [comment] 2016-10-14 18:19
Sorry I thought I had resolved this by changing node versions but I was getting a different error.  Basically building ionic.io.bundle.min.js is failing to generate because 

devDependencies": {
    "ionic": "driftyco/ionic-bower#1.3.1"
  }

in your bower.json isn't resolving.

**Comment by misaacson** [comment] 2016-10-14 18:28
Though weirdly even with the error it still manages to upload.

**Comment by pfiaux** [comment] 2016-10-17 11:12
I'm getting a similar error coming from core-js inside of karma. It looks like https://github.com/driftyco/ionic-cli/issues/1111 and https://github.com/driftyco/ionic-cli/issues/1349 are similar issues (a few more show up in [search](https://github.com/driftyco/ionic-cli/search?utf8=%E2%9C%93&q=%27Can%27t+call+method+on++undefined%27&type=Issues)).

It seems you can get it working by removing `.bold` ([suggested here](https://github.com/driftyco/ionic-cli/issues/1038#issuecomment-234997779)).

In the case of the error above the problem is in ionic-app-lib/lib/upload.js lines 150 & 151. Removing these 2 causes it to succeed.

The real question is why does a locally installed karma using core-js cause errors to be thrown by ionic-app-lib?

**Closed** 2018-07-12 16:15 UTC
Labels: ionitron: old major version
