### ISSUE TITLE
Ionic 2 Tab component Maximum call stack size exceed

### ISSUE THREAD

**Issue by granthoff1107** [ionic-team/ionic-cli#2480] opened 2017-06-29 03:02 UTC
Seems like this is a common problem for Ionic2.   I have a layout component in which I would like to wrap all my pages in which looks like so:

    <ion-header>
      <ion-navbar>
        <button ion-button icon-only menuToggle>
          <ion-icon name="menu"></ion-icon>
        </button>
        <ion-title>
          {{pageName}}
        </ion-title>
      </ion-navbar>
    </ion-header>
    <ng-content>
    </ng-content>
    <ion-footer>
      <ion-toolbar>
        <ion-tabs>
         <ion-tab [root]="usersPage" tabTitle="Chat" tabIcon="chat"></ion-tab>
        </ion-tabs>
      </ion-toolbar>
    </ion-footer>

And Typescript file which looks like so:

    export class AstootLayoutComponent {
    
        @Input() pageName: string;

        usersPage: any = UsersPage;
        profilePage: any = ProfilePage;
    }

In the layout I reference my root Users page who HTML looks like so:

    <astoot-layout [pageName]="pageName">
      <ion-content padding>
        <page-list-base [detailPageType]="userDetailType" [baseProvider]="baseProvider" [config]="pageListConfiguration"></page-list-base>
      </ion-content>
    </astoot-layout>

just incase it's need my Type script looks like so:

     export class UsersPage {

        public pageName: string = "Users";

        public userDetailType: any = ProfilePage;
        public pageListConfiguration: PageListConfiguration = { canDelete: false, canCreate: true };

      constructor(public navCtrl: NavController, public navParams: NavParams, public baseProvider: Users) {
      
      }
    }

When my Layout Component Root page does not contain my layout component everything works fine, but when it does a forever loops seems to be created.  

1.  How can I reuse this component?
2.  What can I do to make my project work again?
3.  Why is this not in the Tabs documentation?

**Comment by janpio** [comment] 2017-06-29 12:06
That doesn't sound like an issue with Ionic CLI at all, more a thing to discuss at the forum at https://forum.ionicframework.com/

**Comment by granthoff1107** [comment] 2017-06-29 13:32
How is this not an ionic issue?

  Your documentation does not specify that's not allowed?  

Nesting components is common functionality of angular if a component does not support that that is an issue.

My guess is only presumably the issue and it could be related to something entirely different.

So can I get confirmation that this is either expected behavior and that the documentation needs to be update? Or is this an even bigger ionic issue?

**Comment by janpio** [comment] 2017-06-29 13:50
You opened an issue for Ionic CLI, the command line interface for Ionic. You are in the wrong place here.

**Comment by Sampath-Lokuge** [comment] 2017-06-29 13:54
@granthoff1107 Use this : https://github.com/ionic-team/ionic/issues

**Comment by janpio** [comment] 2017-06-29 13:57
Even posted there this is not really an issue but a (community) support request - which are happily answered on the forum.

**Comment by GrantHoffman** [comment] 2017-06-29 14:49
Thanks

**Comment by jgw96** [comment] 2017-07-05 20:42
closing as a duplicate of https://github.com/ionic-team/ionic/issues/12206

**Closed** 2017-07-05 20:42 UTC
