### ISSUE TITLE
ionic serve doesn't work (ionic 4.0.3)

### ISSUE THREAD

**Issue by marcosromeroj** [ionic-team/ionic-cli#3472] opened 2018-08-02 15:12 UTC
**Description:**

"ionic serve" or "ionic serve -c" doesn't work.

I am getting infinity messages: [INFO]  Waiting for connectivity with ionic-app-scripts...

**Output:**
[app-scripts] [17:08:03]  ionic-app-scripts 3.1.11
[app-scripts] [17:08:03]  watch started ...
[app-scripts] [17:08:03]  build dev started ...
[app-scripts] [17:08:03]  clean started ...
[app-scripts] [17:08:03]  clean finished in 16 ms
[app-scripts] [17:08:03]  copy started ...
[app-scripts] [17:08:03]  deeplinks started ...
[app-scripts] [17:08:03]  deeplinks finished in 16 ms
[app-scripts] [17:08:03]  transpile started ...
[app-scripts] [17:08:06]  transpile finished in 3.28 s
[app-scripts] [17:08:06]  preprocess started ...
[app-scripts] [17:08:06]  preprocess finished in less than 1 ms
[app-scripts] [17:08:06]  webpack started ...
[app-scripts] [17:08:06]  copy finished in 3.47 s
[app-scripts] [17:08:12]  webpack finished in 5.83 s
[app-scripts] [17:08:12]  sass started ...
[app-scripts] Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[app-scripts] [17:08:13]  sass finished in 1.14 s
[app-scripts] [17:08:13]  postprocess started ...
[app-scripts] [17:08:13]  postprocess finished in 16 ms
[app-scripts] [17:08:13]  lint started ...
[app-scripts] [17:08:13]  build dev finished in 10.43 s
[app-scripts] [17:08:13]  watch ready in 10.51 s
[app-scripts] [17:08:16]  lint finished in 2.79 s
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...

**My `ionic info`:**

Ionic:

   ionic (Ionic CLI)  : 4.0.3
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

System:

   NodeJS : v8.9.4
   npm    : 5.7.1
   OS     : Windows 10

**Other Information:**

But If I use: "ionic-app-scripts serve --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 --consolelogs --nobrowser"
It works, but I have to enter address manually on DevApp because it doesn't detect apps.

**Comment by dwieeb** [comment] 2018-08-02 19:24
@marcosromeroj Can you try `ionic serve --local` ?

**Comment by marcosromeroj** [comment] 2018-08-02 19:52
Yes. It works.

**Comment by dwieeb** [comment] 2018-08-03 00:27
@marcosromeroj I believe you are experiencing the same problem as in [this issue](https://github.com/ionic-team/ionic-cli/issues/3473). So, I'm closing this as a duplicate. Thank you for reporting the issue! Please subscribe to the other issue for updates.

Duplicate of https://github.com/ionic-team/ionic-cli/issues/3473

**Comment by dwieeb** [comment] 2018-08-03 00:28
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3473

**Closed by dwieeb** 2018-08-03 00:27 UTC
Labels: triage
