### ISSUE TITLE
Livereload gives processDebugResources error

### ISSUE THREAD

**Issue by prantikv** [ionic-team/ionic-cli#2961] opened 2018-01-18 11:50 UTC
**Description:**
`Ionic cordova run` works, but `ionic cordova run android -lc`  gives the following error

```
UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources
 UP-TO-DATE

:processDebugManifest

UP-TO-DATE
:processDebugResources
 FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.789 secs
(node:5492) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
(node:5492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Steps to Reproduce:**

**My `ionic info`:**
```


    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 25.2.5
    Node              : v8.9.1
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : I:\DEVELOPMENT PROGRAMS\android-sdk-windows

Misc:

    backend : pro
```

**Comment by dwieeb** [comment] 2018-07-12 18:36
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2961

**Closed by dwieeb** 2018-07-12 18:36 UTC
