### ISSUE TITLE
Livereload (-l, --livereload) and console not work in 5.0.0 version on emulator

### ISSUE THREAD

**Issue by brcontainer** [ionic-team/ionic-cli#4007] opened 2019-06-04 20:04 UTC
**Description:**

Running command `ionic run android -l` work fine in 4.2.0 version, when I edit a file liveload update app in emulator, but if I install ionic-cli 5.0.0, this not work, load normaly in after install application, but liveload not refresh

**Note:** liveload in 5.0.0 work fine in localhost (browser) when using ionic-cli@5.0.0

**Steps to Reproduce:**

- Install npm i ionic@5.0.0 -g
- Create a simple project
- Enter in project folder `cd project1` (an example)
- Execute `ionic run android -l`
- Edit a file in `projetct1/src` folder
- put in any script file (.ts, .js, others) a `console.log('MY TESTE');`

**Output:**

Does not display the output of "console.log"

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI) : 5.0.0

System:

   NodeJS : v10.16.0
   npm    : 6.9.0
   OS     : Windows 10
```

**Other Information:**

may be related to this problem: https://github.com/ionic-team/ionic-cli/issues/4006

**Comment by dwieeb** [comment] 2019-06-04 22:06
@brcontainer What's the output of `ionic info` _inside your project_?

**Comment by brcontainer** [comment] 2019-06-04 23:00
> @brcontainer What's the output of `ionic info` _inside your project_?

Create "from zero", see log ("steps"):

```
C:\Users\Inphinit\myApp>ionic cordova run android -l
> ng.cmd run app:ionic-cordova-serve --host=localhost --port=8100 --platform=android
[INFO] Waiting for connectivity with ng...

[INFO] Development server running!

       Local: http://localhost:8100

       Use Ctrl+C to quit this process

> cordova.cmd build android
[ng] Date: 2019-06-04T22:40:30.184Z
[ng] Hash: 280e937f0140d6f73e93
[ng] Time: 11983ms
[ng] chunk {common} common.js, common.js.map (common) 20.2 kB  [rendered]
[ng] chunk {cordova} cordova.js, cordova.js.map (cordova) 71.6 kB [entry] [rendered]
[ng] chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 285 kB [initial] [rendered]
[ng] chunk {main} main.js, main.js.map (main) 32 kB [initial] [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 237 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 8.9 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 87.9 kB [initial] [rendered]
[ng] chunk {tab1-tab1-module} tab1-tab1-module.js, tab1-tab1-module.js.map (tab1-tab1-module) 6.48 kB  [rendered]
[ng] chunk {tab2-tab2-module} tab2-tab2-module.js, tab2-tab2-module.js.map (tab2-tab2-module) 4.6 kB  [rendered]
[ng] chunk {tab3-tab3-module} tab3-tab3-module.js, tab3-tab3-module.js.map (tab3-tab3-module) 4.6 kB  [rendered]
[ng] chunk {tabs-tabs-module} tabs-tabs-module.js, tabs-tabs-module.js.map (tabs-tabs-module) 7.63 kB  [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 4.37 MB [initial] [rendered]
[INFO] ... and 173 additional chunks
[ng] i ｢wdm｣: Compiled successfully.
> native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --connect --forward 8100:8100
[native-run] No hardare devices found, attempting emulator...
[native-run] Selected emulator emulator-5554
[native-run] Forwarded device port 8100 to host port 8100
[native-run] Installing platforms\android\app\build\outputs\apk\debug\app-debug.apk...
[native-run] Starting application activity io.ionic.starter/io.ionic.starter.MainActivity...
[native-run] Run Successful
[native-run] Waiting for app to close...
[ng] i ｢wdm｣: Compiling...
[ng] i ｢wdm｣: wait until bundle finished: /assets/icon/favicon.png
[ng] Date: 2019-06-04T22:43:59.723Z - Hash: 9ab665e490a37ef57272 - Time: 14475ms
[ng] 184 unchanged chunks
[ng] chunk {main} main.js, main.js.map (main) 32 kB [initial] [rendered]
[ng] i ｢wdm｣: Compiled successfully.
```

My `ionic info`:

```
Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\new_g\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.2

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

I understand that I can use `chrome://inspect` (work fine with log), but the question is really about the terminal/cmd, actually memory is something that during development I try to save and I use another browser and not the chrome, the terminal / cmd have always been useful to me with the logs (even though I'm forced to use `console.log(JSON.stringify(myobject))`).

So I will formulate as a doubt, the "console.log" no longer works with the "output" (terminal or cmd)?

Thank you in advance for your commitment and incredible guidance.

**Comment by dwieeb** [comment] 2019-06-05 04:01
@brcontainer I have confirmed that there is an issue with `--consolelogs` when using port forwarding.  I made a release of the CLI to address this issue (5.0.1). Please update and test: `npm i -g ionic@latest`.

However, I'm not able to reproduce your claim that livereload is broken on an emulator.

**Comment by brcontainer** [comment] 2019-06-06 15:30
> However, I'm not able to reproduce your claim that livereload is broken on an emulator.

I @dwieeb, I no longer noticed, the reason for this is that before (version 4.2.0) there was a "toast" at the top of the app screen:

![toast](https://user-images.githubusercontent.com/4368952/59045507-94693a80-8856-11e9-9180-663948b5540e.png)

I no longer noticed, the reason for this is that before (version 4.2.0) there was a "toast" at the top of the app screen:

Now (5.0.0) the app simply reloads without showing the "toast", sometimes it was so fast I did not notice it.

If I understand, will not you actually display the "building ..." at the top of the app, or am I bugging and really a problem?

**Comment by dwieeb** [comment] 2019-06-06 21:28
Hmm.. I thought Ionic 3 (using `ionic-app-scripts`) has the toast but Ionic 4 (using `@angular/cli`) doesn't. Gonna close this then! 👍

**Closed by dwieeb** 2019-06-06 21:28 UTC
Labels: triage
