### ISSUE TITLE
Error while parsing Capacitor CLI version.

### ISSUE THREAD

**Issue by nchrysis** [ionic-team/ionic-cli#4720] opened 2021-06-15 07:43 UTC
**Description:**
Running command: `ionic cap run android -l --external` failed instantly with message: 
`[ERROR] Error while parsing Capacitor CLI version.`
This happens on versions of `@ionic/cli` >= 6.16.0. On versions earlier than 6.16.0 app runs successfully with no problems.
I had installed latest version of @ionic/cli with the command: `npm i -g @ionic/cli`

ionic cap run android -l --external --verbose
**Output:**

  ```
ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cap', 'run', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, l: true, external: true, project: null, '--': [] } +2ms
  ionic:lib:project Project type from config: @ionic/react (react) +0ms
  ionic:lib:project Project details: { context: 'app', type: 'react', errors: [], configPath: '/home/USER/APP/PATH/ionic.config.json' } +1ms
  ionic Context: { binPath: '/home/USER/.npm-global/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/home/USER/.npm-global/lib/node_modules/@ionic/cli', execPath: '/home/USER/APP/PATH/', version: '6.16.1' } +0ms
[ERROR] Error while parsing Capacitor CLI version.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 0 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +0ms
```

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.16.3 (/home/USER/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.6.9

Capacitor:

   Capacitor CLI   : [warn] The hideLogs configuration option has been deprecated. Please update to use loggingBehavior instead. 3.0.1
   @capacitor/core : 3.0.1

Utility:

   cordova-res : not installed
   native-run  : 1.4.0

System:

   NodeJS : v14.16.0 (/usr/bin/node)
   npm    : 7.15.1
   OS     : Linux 5.9
```
Using version 6.15.0 of @ionic/cli seems to have fixed the issue for me but sadly I cannot use the latest version yet.

**Comment by ItayElgazar** [comment] 2021-06-22 19:58
same here. any ideas?

**Comment by ItayElgazar** [comment] 2021-06-27 17:55
bump?

**Comment by jcesarmobile** [comment] 2021-07-08 15:23
there was an issue open on Capacitor repo about capacitor doctor command not working on linux

https://github.com/ionic-team/capacitor/issues/3747

but looks like it works fine in Capacitor 3

can you try running `npx cap doctor` directly and if you get an error comment on the issue I provided?

**Comment by jcesarmobile** [comment] 2021-07-08 15:33
I've been able to reproduce, the problem is you have `hideLogs` in you `capacitor.config.json` file, which is deprecated, which makes the CLI show a warning about it being deprecated, which breaks the version parsing.

You can solve it by moving to `loggingBehavior`, but should be fixed anyway

**Comment by nchrysis** [comment] 2021-07-08 17:15
Today I changed to loggingBehavior because I saw that warning. Have not yet bumped @ionic/cli to latest version. Will let you know if it fixed the issue for me. Thank you very much!

**Comment by jcesarmobile** [comment] 2021-07-09 15:57
Will be fixed in next @capacitor/cli release
https://github.com/ionic-team/capacitor/pull/4813

**Closed as completed by jcesarmobile** 2021-07-09 15:57 UTC
Labels: triage

**Comment by sudiptosarkar** [comment] 2025-07-23 18:32
@jcesarmobile, I'm getting the same error. Here are the relevant info you may need:

## npx cap doctor

```
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 7.4.2
  @capacitor/core: 7.4.2
  @capacitor/android: 7.4.2
  @capacitor/ios: 7.4.2

Installed Dependencies:

  @capacitor/android: 7.4.2
  @capacitor/ios: 7.4.2
  @capacitor/core: 7.4.2
  @capacitor/cli: 7.4.2

[success] Android looking great! 👌
[error] Xcode is not installed
```

## npx ionic info

```
Ionic:

   Ionic CLI                     : 7.2.1
   Ionic Framework               : @ionic/angular 8.6.5
   @angular-devkit/build-angular : 20.1.2
   @angular-devkit/schematics    : 20.1.2
   @angular/cli                  : 20.1.2
   @ionic/angular-toolkit        : 12.2.0

Capacitor:

   Capacitor CLI      : 7.4.2
   @capacitor/android : 7.4.2
   @capacitor/core    : 7.4.2
   @capacitor/ios     : 7.4.2

Utility:

   cordova-res : not installed globally
   native-run  : 2.0.1

System:

   NodeJS : v22.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 10.9.2
   OS     : Windows 10
```

**Comment by sudiptosarkar** [comment] 2025-07-23 18:47
Nevermind, found the problem...

I found the problem by running `npx ionic cap build android --verbose`. The parameter to notice here is the `--verbose`.

That output had a custom log I had added, which was getting printed when ionic was calling `cap config --json`. That was causing JSON parsing to fail.

This is what (the last part of) my `capacitor.config.ts` looked like before I removed the logs and that solved the problem:

```typescript
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'org.example.myproject',
  appName: 'MyExampleProject',

  .
  .
  .

  if (process.env['BUILD_ENV'] === 'local') {
    console.log('Applying local build configuration');
    config.android!.allowMixedContent = true;
    config.server = { hostname: 'android.local.myproject.example.org', androidScheme: 'http', cleartext: true };
  } else if (process.env['BUILD_ENV'] === 'dev') {
    console.log('Applying dev build configuration');
    config.server = { hostname: 'android.dev.myproject.example.org' };
  }
```

I'm using env variables for handling CORS issues, and had added logging in there to ensure the config changes were getting added.
Weird part is, this was working before. Then it stopped working for half an hour today, and then it started working again, and then it stopped working again.

Hope this helps someone who faces this issue later.
