### ISSUE TITLE
ionic 5.4.7 ng build --prod is not use environment

### ISSUE THREAD

**Issue by acking** [ionic-team/ionic-cli#4223] opened 2019-11-22 08:53 UTC
ionic 5.4.7
ionic build --prod is not use environment

I set environment use API_Url
I set the environment variable API_Url, the command （ ionic build --prod ） is local, with the command（ng build --prod） a normal

**Comment by zarko-tg** [comment] 2019-11-22 10:24
Confirmed :)

**Comment by JDuqn** [comment] 2019-11-22 10:43
This the same problem as issue #4222 :)

**Comment by dwieeb** [comment] 2019-11-22 16:32
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4222

**Closed by dwieeb** 2019-11-22 16:32 UTC
Labels: triage
