### ISSUE TITLE
ionic-cli not showing logs

### ISSUE THREAD

**Issue by guillermo-varela** [ionic-team/ionic-cli#2638] opened 2017-08-15 12:07 UTC
**Description:**

I have an Ionic 1 app and I'm now using a new PC. After installing ionic-cli 3.8.1 and using `ionic cordova run android -lcs` the app runs on the device, the app run on my Android device, the livereload works, but no console message is shown.

When I check the device's `logcat` the messages are there.

Am I missing something to be able to see the console logs on the command prompt when using ionic-cli?

Thanks.

**Steps to Reproduce:**

In an Ionic 1 project run `ionic cordova run android -lcs`

Example repo: N/A

**My `ionic info`:**

cli packages: (C:\Users\JustAUser\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.8.1
    ionic (Ionic CLI) : 3.8.1

global packages:

    Cordova CLI : 7.0.1
    Gulp CLI    : not installed globally

local packages:

    Cordova Platforms : none
    Ionic Framework   : ionic1 1.2.4

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.1
    npm               : 3.10.10
    OS                : Windows 8.1

**Comment by dwieeb** [comment] 2017-08-15 15:34
Thanks for the bug report! I believe this is a duplicate of this issue: https://github.com/ionic-team/ionic-cli/issues/2548

Let me know if I'm mistaken. Closing for now.

**Closed by dwieeb** 2017-08-15 15:34 UTC
