### ISSUE TITLE
CLI shows update message although I just updated

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#3893] opened 2019-03-06 09:54 UTC
See:

```
E:\Projects\throwaway
λ ionic -v

   _             _
  (_) ___  _ __ (_) ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___|  CLI 4.10.2


  Usage:

    $ ionic <command> [<args>] [--help] [--verbose] [--quiet] [--no-interactive] [--no-color] [--confirm] [options]

  Global Commands:

    config <subcommand> ............. Manage CLI and project config values (subcommands: get, set, unset)
    docs ............................ Open the Ionic documentation website
    info ............................ Print project, system, and environment information
    init ............................ (beta) Initialize existing projects with Ionic
    login ........................... Login to Ionic Appflow
    logout .......................... Logout of Ionic Appflow
    signup .......................... Create an account for Ionic Appflow
    ssh <subcommand> ................ Commands for configuring SSH keys (subcommands: add, delete, generate, list,
                                      setup, use)
    start ........................... Create a new project

  Project Commands:

    You are not in a project directory.


E:\Projects\throwaway
λ npm install -g ionic
C:\Users\Jan\scoop\apps\nvm\current\nodejs\nodejs\ionic -> C:\Users\Jan\scoop\apps\nvm\current\nodejs\nodejs\node_modules\ionic\bin\ionic
+ ionic@4.10.3
removed 1 package and updated 14 packages in 14.751s

E:\Projects\throwaway
λ ionic -v

   _             _
  (_) ___  _ __ (_) ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___|  CLI 4.10.3


  Usage:

    $ ionic <command> [<args>] [--help] [--verbose] [--quiet] [--no-interactive] [--no-color] [--confirm] [options]

  Global Commands:

    config <subcommand> ............. Manage CLI and project config values (subcommands: get, set, unset)
    docs ............................ Open the Ionic documentation website
    info ............................ Print project, system, and environment information
    init ............................ (beta) Initialize existing projects with Ionic
    login ........................... Login to Ionic Appflow
    logout .......................... Logout of Ionic Appflow
    signup .......................... Create an account for Ionic Appflow
    ssh <subcommand> ................ Commands for configuring SSH keys (subcommands: add, delete, generate, list,
                                      setup, use)
    start ........................... Create a new project

  Project Commands:

    You are not in a project directory.



   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 4.10.2 → 4.10.3    │
   │     Run npm i -g ionic to update      │
   │                                       │
   ╰───────────────────────────────────────╯

```

**Comment by dwieeb** [comment] 2019-03-06 14:44
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3872

**Closed by dwieeb** 2019-03-06 14:44 UTC
Labels: triage
