### ISSUE TITLE
Ionic v1 --livereload net::ERR_INVALID_CHUNKED_ENCODING (livereload.js)

### ISSUE THREAD

**Issue by henlocon** [ionic-team/ionic-cli#3511] opened 2018-08-14 07:52 UTC
**Description:**
Ionic v1 - Livereload is not working in the latest ionic CLI. In Chrome console livereload.js shows an error net::ERR_INVALID_CHUNKED_ENCODING

**Steps to Reproduce:**
`ionic start myApp blank --type=ionic1`

`cd myApp`

`npm install @ionic/v1-toolkit@latest --save-dev`

`ionic cordova emulate android --livereload`

Open Chrome DevTools console, livereload.js will be "Failed to load resource: net::ERR_INVALID_CHUNKED_ENCODING"

If no error, make a change to index.html, wait for livereload and observe error.

**Output:**
Error in Chrome DevTools

![image](https://user-images.githubusercontent.com/41062670/44078291-67ebc6ba-9fa6-11e8-8885-53e3b58a29f1.png)

Alternative error, see below. The source of livereload.js is unchanged.

![image](https://user-images.githubusercontent.com/41062670/44078734-91f38a82-9fa7-11e8-9657-15bd17a54dbc.png)

**My `ionic info`:**

```
C:\temp\myApp>ionic info
[WARN] Error with .\www\lib\ionic\version.json file: FILE_NOT_FOUND, trying .\bower.json.
√ Gathering environment info - done!

Ionic:

   ionic (Ionic CLI) : 4.0.6 (C:\Users\henlocon\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.7.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.1.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\henlocon\AppData\Local\Android\sdk


```

**Other Information:**

@dwieeb, thank you for your help on the previous related issue https://github.com/ionic-team/ionic-cli/issues/3461

I have tried amongst others:
- different networks, including loopback network, to rule out proxy issue.
- emulator and real device.

**Comment by henlocon** [comment] 2018-11-06 14:48
Hi @dwieeb,

I understand this is very low priority...

If you get a chance to look into this, I think changing http-proxy-middleware to proxy-middleware with the related changes will sort the issue.

Thanks

**Comment by dwieeb** [comment] 2018-11-06 21:44
Sorry @henlocon! I get lots of issues coming in. I'm just not able to reproduce this issue. My livereload on Android and iOS is working great with old and new apps for Ionic 1.

https://github.com/chimurai/http-proxy-middleware is vastly more popular than https://github.com/gonzalocasas/node-proxy-middleware#readme, I don't think we want to switch back to it. 

I haven't been able to find any search results for `LiveRload is not defined` either...

Here's my `ionic info`:

```
Ionic:

   ionic (Ionic CLI) : 4.3.1 (/Users/dan/ionic-team/ionic-cli/packages/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.12

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 4 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/dan/Library/Android/sdk)
   NodeJS            : v10.12.0 (/Users/dan/.nvm/versions/node/v10.12.0/bin/node)
   npm               : 6.4.1
   OS                : macOS
   Xcode             : Xcode 10.0 Build version 10A255
```

**Comment by dwieeb** [comment] 2018-11-06 21:45
@henlocon Which AVD are you using for your emulator? I am using Pixel 2. Here's what it looks like in Android Studio: 

<img width="779" alt="image" src="https://user-images.githubusercontent.com/236501/48095692-fc7d7280-e1da-11e8-9a45-ce96029e0cb5.png">

**Comment by henlocon** [comment] 2018-11-07 08:06
Hi @dwieeb,

Thank you for the quick response.

My ionic info differs slightly from yours, see below.  I will update @ionic/v1-toolkit and test, but it might also be a Windows vs Mac issue?!?! I have also tried the same AVD without success.

Don't worry about this too much for now. I came up with the solution below that is working for now.

-----------------
**http-proxy-middleware vs proxy-middleware**

I compared:
`..\node_modules\@ionic\v1-toolkit\dist\lib\serve.js`
and
`..\node_modules\@ionic\app-scripts\dist\dev-server\http-server.js`

v1-toolkit uses:
`const proxyMiddleware = yield Promise.resolve().then(() => require('http-proxy-middleware'));`

app-scripts uses:
`var proxyMiddleware = require("proxy-middleware");`

I copied from "function setupProxies(app)" in http-sever.js and made the following change to v1-toolkit which is now working for me:

```
function attachProxy(app, config) {
    return tslib_1.__awaiter(this, void 0, void 0, function* () {
        const proxyMiddleware = yield Promise.resolve().then(() => require('proxy-middleware'));
        var opts = url.parse(config.target);
        if (config.proxyNoAgent) {
          opts.agent = false;
        }
        opts.rejectUnauthorized = !(config.rejectUnauthorized === false);
        opts.cookieRewrite = config.cookieRewrite;
        app.use(config.mount, proxyMiddleware(opts));
    });
}
```

```
Ionic:

   ionic (Ionic CLI) : 4.3.1 (C:\Users\henlocon\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework   : ionic1 1.3.5
   @ionic/v1-toolkit : 1.0.11

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 20 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\henlocon\AppData\Local\Android\sdk)
   NodeJS            : v10.7.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10

```

**Comment by dwieeb** [comment] 2019-07-31 22:10
Glad to hear you got a workaround going. Given that no one else has had this issue, I think it's safe to close this.

**Closed by dwieeb** 2019-07-31 22:10 UTC
Labels: needs investigation
