### ISSUE TITLE
ionic serve more project

### ISSUE THREAD

**Issue by wangjian1119** [ionic-team/ionic-cli#2942] opened 2018-01-04 08:01 UTC
**Description:**

I run a project. That's right, but when I run another project, I automatically terminate the command. When I terminate the first project, second can run! Help me, thank you.

**Steps to Reproduce:**

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

**Other Information:**

**Comment by wangjian1119** [comment] 2018-01-05 05:24
who can help me

**Comment by dwieeb** [comment] 2018-01-08 21:08
@wangjian1119 Please fill out the issue template.

**Comment by dwieeb** [comment] 2018-01-08 21:10
Likely a duplicate of https://github.com/ionic-team/ionic-cli/issues/2942

**Closed by dwieeb** 2018-01-08 21:10 UTC
