### ISSUE TITLE
can't serve ionic app after updating cli to 4.0.1 

### ISSUE THREAD

**Issue by ashrfadol** [ionic-team/ionic-cli#3431] opened 2018-07-29 08:41 UTC
**Description:**
when running ionic serve or ionic lab I get the underline error.

**Output:**
ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35730 --dev-logger-port 53703 --nobrowser
[app-scripts] [11:32:39]  ionic-app-scripts 3.1.10
[app-scripts] [11:32:39]  watch started ...
[app-scripts] [11:32:39]  build dev started ...
[app-scripts] events.js:183
[app-scripts]       throw er; // Unhandled 'error' event
[app-scripts]       ^
[app-scripts]
[app-scripts] Error: listen EADDRINUSE :::53703
[app-scripts]     at Object._errnoException (util.js:992:11)
[app-scripts]     at _exceptionWithHostPort (util.js:1014:20)
[app-scripts]     at Server.setupListenHandle [as _listen2] (net.js:1355:14)
[app-scripts]     at listenInCluster (net.js:1396:12)
[app-scripts]     at Server.listen (net.js:1480:7)
[app-scripts]     at new WebSocketServer (C:\Users\ashrf\Desktop\Midany\MidanyApp\node_modules\ws\lib\WebSocketServer.js:77:20)
[app-scripts]     at Object.createNotificationServer (C:\Users\ashrf\Desktop\Midany\MidanyApp\node_modules\@ionic\app-scripts\dist\dev-server\notification-server.js:66:15)
[app-scripts]     at C:\Users\ashrf\Desktop\Midany\MidanyApp\node_modules\@ionic\app-scripts\dist\serve.js:58:31
[app-scripts]     at <anonymous>
[app-scripts]     at process._tickCallback (internal/process/next_tick.js:188:7)

[ERROR] A utility CLI has unexpectedly closed.

        The Ionic CLI will exit. Please check any output above for error details.

**My `ionic info`:**

Ionic:

   ionic (Ionic CLI)  : 4.0.1 (C:\Users\ashrf\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : none

System:

   NodeJS : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 10

Environment:

   ANDROID_HOME : not set

**Comment by sachingarg05** [comment] 2018-07-29 08:49
Check if you had another instance of ionic serve already running on your computer, it seems like the port number was already in use, most likely by a previous instance of ionic serve. 

If you are getting this error, try after restarting your computer. Maybe the new cli is not completely closing a running ionic serve instance.

**Comment by dwieeb** [comment] 2018-07-30 16:50
Additionally, you must upgrade to latest `@ionic/app-scripts`. Apologies, I'll put that in the changelog.

**Comment by dwieeb** [comment] 2018-07-30 16:50
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3368

**Closed by dwieeb** 2018-07-30 16:50 UTC
Labels: triage

**Comment by enigma49** [comment] 2018-08-10 17:34
I am getting the same error. I have tried npm install @ionic/lab and the above methods too still it's not working

**Comment by enigma49** [comment] 2018-08-10 17:37
@dwieeb I wrote the originally in ionic3 can you tell me how I can run it in ionic 4?
