### ISSUE TITLE
problems when doing the build of the app on ionic 3

### ISSUE THREAD

**Issue by marvinug** [ionic-team/ionic-cli#3303] opened 2018-06-12 22:01 UTC
ANDROID_HOME=/Users/desarrollomktech/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
(node:3168) UnhandledPromiseRejectionWarning: CordovaError: Requirements check failed for JDK 1.8 or greater
    at /Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/lib/check_reqs.js:370:19
    at _fulfilled (/Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/node_modules/q/q.js:624:44
    at runSingle (/Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/node_modules/q/q.js:137:13)
    at flush (/Users/desarrollomktech/Desktop/Carbox/carboxDrive/platforms/android/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:3168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dwieeb** [comment] 2018-06-12 22:39
Additionally, duplicate of https://github.com/ionic-team/ionic-cli/issues/3115

**Closed** 2018-06-12 22:39 UTC
Labels: ionitron: missing template, triage
