### ISSUE TITLE
ionic cordova run doesn't work after update to Ionic CLI 5 and native-run

### ISSUE THREAD

**Issue by NurGuz23** [ionic-team/ionic-cli#4015] opened 2019-06-08 15:37 UTC
After having updated to Ionic CLI 5 and updated native-run too

The command **ionic cordova run android has stopped working**.

I have everything updated, Android Studio SDK and yours corresponding packages.

```
Ionic info:

Ionic:

   Ionic CLI                     : 5.0.1 (C:\Users\nuria\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.1
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.3.8
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 7 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.4

System:

   NodeJS : v10.15.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```
The error is:

```
native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-debug.apk --device
Error: Command failed: C:\Users\nuria\AppData\Local\Android\Sdk\platform-tools/adb -s RF8M204LVHX shell getprop

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by TorbenJ** [comment] 2019-06-08 23:32
Got the same problem:  
```
Ionic:

   Ionic CLI                     : 5.0.1 (C:\Users\Torben Jonas\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 5 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.4

System:

   Android SDK Tools : 26.1.1 (D:\android-sdk)
   NodeJS            : v10.13.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.4.1
   OS                : Windows 10
```

This is the output of `ionic cordova run android --verbose`  
```
Error: Command failed: D:\android-sdk\platform-tools/adb -s ZY2245PL52 shell getprop

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
[ERROR] An error occurred while running subprocess native-run.

        native-run.cmd android --app platforms\android\app\build\outputs\apk\debug\app-d... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 3 functions +0ms
  ionic:utils-process error while killing process tree for 11992: { Error: Command failed: taskkill /pid 11992 /T /F
  ionic:utils-process ERROR: The process "11992" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:utils-process     at ChildProcess.emit (events.js:182:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:962:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 11992 /T /F' } +64ms
  ionic:utils-process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 11992 /T /F
  ionic:utils-process ERROR: The process "11992" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:utils-process     at ChildProcess.emit (events.js:182:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:962:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 11992 /T /F' } +4ms
  ionic:utils-process error while killing process tree for 18160: { Error: Command failed: taskkill /pid 18160 /T /F
  ionic:utils-process ERROR: The process "18160" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:utils-process     at ChildProcess.emit (events.js:182:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:962:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 18160 /T /F' } +7ms
  ionic:utils-process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 18160 /T /F
  ionic:utils-process ERROR: The process "18160" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:utils-process     at ChildProcess.emit (events.js:182:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:962:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 18160 /T /F' } +5ms
  ionic:utils-process error while killing process tree for 16480: { Error: Command failed: taskkill /pid 16480 /T /F
  ionic:utils-process ERROR: The process "16480" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:utils-process     at ChildProcess.emit (events.js:182:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:962:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 16480 /T /F' } +1ms
  ionic:utils-process onBeforeExit handler: error from function: { Error: Command failed: taskkill /pid 16480 /T /F
  ionic:utils-process ERROR: The process "16480" not found.
  ionic:utils-process
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:289:12)
  ionic:utils-process     at ChildProcess.emit (events.js:182:13)
  ionic:utils-process     at maybeClose (internal/child_process.js:962:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 16480 /T /F' } +1ms
  ionic:utils-process processExit: exiting (exit code: 1) +1ms
```

I tried reinstalling Android SDKs, USB drivers and restarting my computer so far.  
I don't really know what to try next :(

**Comment by quanganh206** [comment] 2019-06-09 07:53
Same problem, and can not run with --project flag

ionic cordova run android --project=mobile-mymobileapp --prod
always return ng run **app:ionic-cordova-build:production** --platform=android --cordova-base-path

**Comment by Ilde314** [comment] 2019-06-10 07:57
Same here, trying to migrate from ionic 3. Reinstalled everything, started a new project and keeps on failing ...

ionic cordova emulate android also fails 

Ionic:

   Ionic CLI                     : 5.0.1 (C:\Users\ildef\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 4 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.4

System:

   NodeJS : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10

**Comment by dwieeb** [comment] 2019-06-10 18:43
Duplicate of https://github.com/ionic-team/native-run/issues/45

**Closed by dwieeb** 2019-06-10 18:43 UTC
Labels: triage
