### ISSUE TITLE
ionic cordova resources --splash not working, 

### ISSUE THREAD

**Issue by rashnk** [ionic-team/ionic-cli#2792] opened 2017-10-10 11:24 UTC
Description
`ionic cordova resources --splash` not working, it does not genereate images, the error message attached as image here

**Steps to Reproduce:**
1. cd into ionic project
2. run `ionic cordova resources --splash`

**Output:**
 Failed!

**My `ionic info`:**

```
$ ionic info

cli packages: (D:\ionic2\vartha\node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.7.0

System:

    Android SDK Tools : 25.2.5
    Node              : v7.7.4
    npm               : 4.1.2
    OS                : Windows 7

Misc:

    backend : legacy
```

![capture](https://user-images.githubusercontent.com/12730428/31384092-13aae184-addb-11e7-88cb-ed0760e9cc98.PNG)
![capture1](https://user-images.githubusercontent.com/12730428/31384093-13e729f0-addb-11e7-8108-ea1c5039037f.PNG)

-->

**Other Information:**
 Links
Forum Post :  [https://forum.ionicframework.com/t/ionic-cordova-resources-returns-error/108329](https://forum.ionicframework.com/t/ionic-cordova-resources-returns-error/108329)

[https://forum.ionicframework.com/t/constant-503-errors-from-resources/108312/8](https://forum.ionicframework.com/t/constant-503-errors-from-resources/108312/8)

**Comment by jm-peytz** [comment] 2017-10-10 12:01
I have the exact same issue, cannot install since building resources fails hard. Looks like it partly works...

`✖ Generating platform resources: 13 / 32 complete - failed!`

**Comment by tarazzito** [comment] 2017-10-10 12:36
I have the same issue. It was working yesterday but today it doesn't work anymore
Error is "Uploading source images to prepare for transformations - failed!"

+ ionic cordova resources
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
✖ Uploading source images to prepare for transformations - failed!
HTTP Error 503: POST https://res.ionic.io/api/v1/upload
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>

**Comment by dwieeb** [comment] 2017-10-10 14:41
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2793

**Closed by dwieeb** 2017-10-10 14:41 UTC
