### ISSUE TITLE
Ionic command fails with error TypeError: Cannot set property pathExists

### ISSUE THREAD

**Issue by bluemeerkat** [ionic-team/ionic-cli#4439] opened 2020-05-13 17:17 UTC
**Description:**
I just installed ionic and cordova for first time using: "npm install ionic cordova -g" on Windows 10, having also just installed Node.js for the first time. The two packages appeared to install (give or take some "deprecated" warnings).
The tail end of the output was this, so I guess those are the package versions.
+ cordova@9.0.0
+ ionic@5.4.16

(I then tried "cordova -v" -> which outputs 9.0.0 (cordova-lib@9.0.1) happily enough)

But on trying to run "ionic -v" (or any other parameters), I get the errors shown in the output section below.

I did see a similar error reported related to a version of ionic/cli (6.9.0) in the past 24 hours  (issues #4436)... but that seems to relate to a different version. Furthermore, that version is supposedly now fixed... and I *just* downloaded and installed ionic, so presumably have the latest code.

**Steps to Reproduce:**
$ npm install ionic cordova -g
$ ionic -v

**Output:**
_Running ionic -v:_
C:\Users\david\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\utils-fs\dist\index.js:168
exports.pathExists = pathExists;
                   ^

TypeError: Cannot set property pathExists of #<Object> which has only a getter
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\utils-fs\dist\index.js:168:20)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\david\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-framework\utils\node.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)

_Running npm install ionic cordova -g_  
(just for completeness in case it gives a clue).

$ npm install ionic cordova -g
npm WARN deprecated ionic@5.4.16: The Ionic CLI now uses ✨ @ionic/cli ✨ for its package name! 👉 https://twitter.com/ionicframework/status/1223268498362851330
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Users\david\AppData\Roaming\npm\cordova -> C:\Users\david\AppData\Roaming\npm\node_modules\cordova\bin\cordova
C:\Users\david\AppData\Roaming\npm\ionic -> C:\Users\david\AppData\Roaming\npm\node_modules\ionic\bin\ionic
+ cordova@9.0.0
+ ionic@5.4.16
added 671 packages from 396 contributors in 38.315s

**My `ionic info`:**
Can't get this since ionic command fails, sorry.

**Other Information:**
(I'm a newbie in this area - although an experienced engineer. So please tailor any follow up questions/instructions bearing that in mind. Thanks a lot for any help.)

**Comment by dwieeb** [comment] 2020-05-13 19:02
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4436

**Closed by dwieeb** 2020-05-13 19:02 UTC
Labels: triage
