### ISSUE TITLE
Bug: CLI cannot identify the Windows 11

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-cli#5067] opened 2023-12-12 12:15 UTC
**Description:**
CLI cannot identify the Windows 11. It shows as Windows 10. i.e. I have Microsoft Windows 11 Pro PC

**Steps to Reproduce:**
ionic info

**Output:**
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package.json'

       Require stack:
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic
[WARN] Error loading @capacitor/android package.json: Error: Cannot find module '@capacitor/android/package.json'

       Require stack:
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 7.1.1 (C:\Users\Sampath\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.6.0
   @angular-devkit/build-angular : 16.2.10
   @angular-devkit/schematics    : 16.2.10
   @angular/cli                  : 16.2.10
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.0.0
   @capacitor/android : not installed
   @capacitor/core    : 5.0.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.4

System:

   NodeJS : v18.18.2 (C:\Program Files\nodejs\node.exe)
   npm    : 9.8.1
   OS     : Windows 10

**My `ionic info`:**

```
<paste here>
```

**Other Information:**

**Comment by jcesarmobile** [comment] 2023-12-12 17:28
duplicate of https://github.com/ionic-team/ionic-cli/issues/4961

**Closed as not planned by jcesarmobile** 2023-12-12 17:28 UTC
Labels: triage
