### ISSUE TITLE
Unable to find command - ionic serve after upgrade to 4.0.2 from 3.20.0

### ISSUE THREAD

**Issue by shreejibawa** [ionic-team/ionic-cli#3445] opened 2018-07-31 06:22 UTC
**Description:**
I just upgraded Ionic Cli from 3.20.0 to 4.0.2 and tried to run `ionic serve` and it shows error `Unable to find command.`

`ionic info` also does not work.

Please check image.

![image](https://user-images.githubusercontent.com/8849256/43441354-2bd6dd16-94b8-11e8-9b76-f65d1523b3fb.png)

**Comment by Losnen** [comment] 2018-07-31 08:03
Same problem here

**Comment by jacquesdev** [comment] 2018-07-31 10:13
You probably need to install it globally?

**Comment by Losnen** [comment] 2018-07-31 10:14
It was installed globally

**Comment by mluis** [comment] 2018-07-31 14:39
Same here.

**Comment by dwieeb** [comment] 2018-07-31 16:09
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3393

**Comment by dwieeb** [comment] 2018-07-31 16:10
I believe the solution is to uninstall fully and then re-install:

```
npm uninstall -g ionic
npm install -g ionic
```

**Comment by aelshamy** [comment] 2018-07-31 16:37
I got this if I trying to upgrade from 4.0.1 

`npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ionic/cli-framework@1.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ionic'
npm ERR! notarget`

**Comment by dwieeb** [comment] 2018-07-31 17:35
I've validated that the dependencies are correct for 4.0.2 release: https://unpkg.com/ionic@4.0.2/package.json

I'm guessing this is a local issue related to npm. Please make sure you are using either the latest npm 5 or 6, run `npm cache clear`, do a full uninstall and reinstall of `ionic`.

**Comment by aelshamy** [comment] 2018-07-31 17:49
I have `npm 6.2.0` and `node 10.7.0` I did `npm cache clear --force` full uninstall ionic and try to install the latest version and I got the same error

**Comment by dwieeb** [comment] 2018-07-31 18:08
@aelshamy What is the output of `npm info @ionic/cli-framework@1.0.1` ?

**Comment by aelshamy** [comment] 2018-07-31 18:11
@dwieeb nothing when I ran it

**Comment by dwieeb** [comment] 2018-07-31 18:13
@aelshamy Are you using a custom registry? Your local npm cli is simply not acknowledging that 1.0.1 exists. 👉 https://www.npmjs.com/package/@ionic/cli-framework

**Comment by aelshamy** [comment] 2018-07-31 18:19
@dwieeb oh yes I am using a custom one. let me switch npm

**Comment by dwieeb** [comment] 2018-07-31 19:00
Closing as duplicate of resolved issue: https://github.com/ionic-team/ionic-cli/issues/3393

If the issue is not resolved, please let me know and I will happily re-open!

**Closed by dwieeb** 2018-07-31 19:00 UTC
Labels: triage

**Comment by Muttura** [comment] 2020-09-27 08:04
(_) ___  _ __ (_) ___
  | |/ _ \| '_ \| |/ __|
  | | (_) | | | | | (__
  |_|\___/|_| |_|_|\___| CLI 6.11.9


  Usage:

    $ ionic <command> [<args>] [--help] [--verbose] [--quiet] [--no-interactive] [--no-color] [--confirm] [options]

  Global Commands:

    completion ...................... (experimental) Enables tab-completion for Ionic CLI commands.
    config <subcommand> ............. Manage CLI and project config values (subcommands: get, set, unset)
    docs ............................ Open the Ionic documentation website
    info ............................ Print project, system, and environment information
    init ............................ (beta) Initialize existing projects with Ionic
    login ........................... Log in to Ionic
    logout .......................... Log out of Ionic
    signup .......................... Create an Ionic account
    ssh <subcommand> ................ Commands for configuring SSH keys (subcommands: add, delete, generate, list,
                                      setup, use)
    start ........................... Create a new project

  Project Commands:

    build ........................... Build web assets and prepare your app for any platform targets
    capacitor <subcommand> .......... Capacitor functionality (subcommands: add, build, copy, open, run, sync, update)
                                      (alias: cap)
    cordova <subcommand> ............ Cordova functionality (subcommands: build, compile, emulate, platform, plugin,
                                      prepare, requirements, resources, run) (alias: cdv)
    deploy <subcommand> ............. (paid) Appflow Deploy functionality (subcommands: add, build, configure, manifest)    doctor <subcommand> ............. Commands for checking the health of your Ionic project (subcommands: check, list,
                                      treat)
    enterprise <subcommand> ......... (paid) Manage Ionic Enterprise features (subcommands: register)
    generate ........................ Automatically create framework features (alias: g)
    git <subcommand> ................ (paid) Commands relating to managing Appflow git (subcommands: remote)
    integrations <subcommand> ....... Manage various integrations in your app (subcommands: disable, enable, list)
                                      (aliases: i, integration)
    link ............................ (paid) Connect local apps to Ionic
    package <subcommand> ............ (paid) Appflow package functionality (subcommands: build, deploy)
    repair .......................... Remove and recreate dependencies and generated files
    serve ........................... Start a local dev server for app dev/testing (alias: s)
    ssl <subcommand> ................ (experimental) Commands for managing SSL keys & certificates (subcommands:
                                      generate)

**Comment by Muttura** [comment] 2020-09-27 08:04
I GOT ERROR
