### ISSUE TITLE
[ionic 4] ionic lab is not adding mode="md" in html tag for ios

### ISSUE THREAD

**Issue by gaurav-chandra** [ionic-team/ionic-cli#3854] opened 2019-02-08 10:33 UTC
# Bug Report

**Ionic version:**
[x] 4.0.0

**Current behavior:**
this does not add mode="md" to html tag when using ```ionic lab```
```
IonicModule.forRoot({
      mode: 'md'
    })
```
**Expected behavior:**
mode="md" should be added to the html tag

**Steps to reproduce:**
use ionic lab > inspect ios frame > check html tag

**Other information:**

**Ionic info:** 

```
   ionic (Ionic CLI)             : 4.10.2 (C:\Users\Gaurav's PC\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.0
   @angular-devkit/build-angular : 0.11.4
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.1.4
   @ionic/angular-toolkit        : 1.2.2

```

**Comment by dwieeb** [comment] 2019-02-08 17:25
@gaurav-chandra Ionic Lab _forces_ the mode for the device frames, which is different from an actual device. It will be md mode on iOS devices.

I don't think Ionic Lab is particularly useful for you if you're only using md styles.

**Comment by gaurav-chandra** [comment] 2019-02-09 03:25
In ionic 3, mode md was forced in lab also. The reason to use lab was to check whether he app looks same across ios and android or not.

**Comment by dwieeb** [comment] 2019-02-11 20:18
@gaurav-chandra Sorry, I think I misunderstood you. The `IonicModule` configuration confused me. Is this by chance a duplicate of https://github.com/ionic-team/ionic-cli/issues/3687?

**Comment by gaurav-chandra** [comment] 2019-02-12 02:13
Probably a duplicate but in #3687, md is being forced without configuring for it. In this I want md to be forced. Looks like ionic config needs to be looked at.

**Comment by liamdebeasi** [comment] 2023-01-09 14:26
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.

**Closed by liamdebeasi** 2023-01-09 14:26 UTC
Labels: triage
