### ISSUE TITLE
ionic-serve --no-open (not working) (ionic 5.4.7 issue)

### ISSUE THREAD

**Issue by SergioSuarezDev** [ionic-team/ionic-cli#4224] opened 2019-11-22 12:21 UTC
**Description:**

ionic-serve --no-open (not working)

**Steps to Reproduce:**

**Output:**

**My `ionic info`:**

```
Ionic:

   Ionic CLI                     : 5.4.7 (/Users/sergio/.nvm/versions/node/v13.0.1/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.803.19
   @angular-devkit/schematics    : 8.3.19
   @angular/cli                  : 8.3.19
   @ionic/angular-toolkit        : 2.1.1

Capacitor:

   Capacitor CLI   : 1.3.0
   @capacitor/core : 1.3.0

Utility:

   cordova-res : 0.8.1 
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/sergio/Library/Android/sdk)
   NodeJS            : v13.0.1 (/Users/sergio/.nvm/versions/node/v13.0.1/bin/node)
   npm               : 6.12.0
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500```


**Other Information:**
<!--
e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links,
forum links, etc
-->

**Comment by dwieeb** [comment] 2019-11-22 16:32
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4222

**Closed by dwieeb** 2019-11-22 16:32 UTC
Labels: triage
