### ISSUE TITLE
404 Not Found - GET http://registry.npmjs.org/@ionic%2fcli-framework

### ISSUE THREAD

**Issue by marekgaj** [ionic-team/ionic-cli#4211] opened 2019-11-11 17:38 UTC
**Description:**
I'm trying to install ionic using npm on a new laptop but it's returning an error

**Steps to Reproduce:**
I run the following command:
`npm install -g ionic`

**Output:**
```
npm WARN deprecated superagent@4.1.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm ERR! code E404
npm ERR! 404 Not Found - GET http://registry.npmjs.org/@ionic%2fcli-framework - User not found
npm ERR! 404 
npm ERR! 404  '@ionic/cli-framework@3.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ionic'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2019-11-11T17_37_29_324Z-debug.log
```

**My `ionic info`:**
n/a

**Comment by dwieeb** [comment] 2019-11-11 20:37
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3562 and https://github.com/ionic-team/ionic-cli/issues/3656

**Closed by dwieeb** 2019-11-11 20:37 UTC
Labels: triage
