### ISSUE TITLE
v3.9.2 ionic-cli caused "Failed to load resource:  net::ERR_FILE_NOT_FOUND"

### ISSUE THREAD

**Issue by jing-zhou** [ionic-team/ionic-cli#2707] opened 2017-08-29 10:10 UTC
**Description:**

"Failed to load resource:  net::ERR_FILE_NOT_FOUND" occurred after upgrade to v3.9.2

**Steps to Reproduce:**

1. upgrade to v3.9.2
2. run "ionic cordova run android"
3. enter "chrome://inspect/#devices" in the address bar of chrome browser
4. select the apps, error logs emerges in the console area (see first screen shot below).
5. downgrade to v3.7.0, repeat from step 2 to 4, errors disappeared  (see second screen shot below).

Example repo: 

**Output:**

![failed-to-load-resource](https://user-images.githubusercontent.com/3517418/29815982-174cad84-8ce5-11e7-9356-9ca2edaf3784.png)

![resource-loaded](https://user-images.githubusercontent.com/3517418/29815994-21898f7e-8ce5-11e7-9416-6ca90423fc0f.png)

**My `ionic info`:**

wjz@bj:~/ion/vajra$ ionic info 
? The Ionic CLI (local version) has an update available (3.7.0 => 3.9.2)! Would you like to install it? No
[INFO] Not automatically updating your CLI. You can update manually:
       
       npm install --save-dev --save-exact ionic@latest
       

cli packages: (/home/wjz/ion/vajra/node_modules)

    @ionic/cli-plugin-cordova       : 1.6.2
    @ionic/cli-plugin-ionic-angular : 1.4.1
    @ionic/cli-utils                : 1.7.0
    ionic (Ionic CLI)               : 3.7.0

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.0.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 25.2.5
    Node              : v8.2.1
    OS                : Linux 4.4
    npm               : 5.3.0 

**Other Information:**

note from the above "ionic info" section  that I have already downgraded to v3.7.0

**Comment by mebibou** [comment] 2017-08-29 14:41
duplicate of #2675

**Comment by dwieeb** [comment] 2017-08-29 22:04
Indeed, looks like a bug with 3.9.2. Closing for the duplicate ^

**Closed by dwieeb** 2017-08-29 22:04 UTC

**Comment by Barathwaja** [comment] 2017-09-10 09:48
I'm also receiving same error **file not found** for **fonts**.


![screenshot from 2017-09-10 15-09-26](https://user-images.githubusercontent.com/5066436/30247905-35875d4e-963b-11e7-9e17-df9dd5338a41.png)

**Comment by dwieeb** [comment] 2017-09-11 05:12
@Barathwaja Those are the same resources as in the original issue. The fix is coming to `@ionic/app-scripts` soon. See https://github.com/ionic-team/ionic-cli/issues/2675#issuecomment-327686819.

**Comment by mebibou** [comment] 2017-09-20 08:36
@dwieeb actually no it is not the same issue, just realized this now. #2675 is talking about loading custom fonts, which now works, but I have the same problem as reported here which is that the default `Roboto` fonts are not included in the `assets` folder for Android, because they are supposed to be built-in. CF my issue on the [app-scripts](https://github.com/ionic-team/ionic-app-scripts/issues/1197)

**Comment by rolandjitsu** [comment] 2017-10-14 18:53
I'm seeing similar behaviour. Default Roboto fonts are not loaded for production builds, only for dev builds.
