### ISSUE TITLE
ionic/cli@6.20.2 causing xcode task to fail in Azure Devops pipeline

### ISSUE THREAD

**Issue by mdenieffe** [ionic-team/ionic-cli#4919] opened 2022-10-05 21:48 UTC
**Description:**

We use Azure Devops to build our iOS App, but in the last few days the iOS build as started failing on the Azure Devops Xcode@5 task. 

**Steps to Reproduce:**

The flow of the pipeline is as following (shortened for convenience);

```
steps:
   ...
    // 1. install the @ionic/cli, this installs the latest version currently 6.20.2
    - script: |
            npm install -g @ionic/cli` // installs the latest version 6.20.2

   // 2. run ionic cap sync ios command
    - script: |
          ionic cap sync ios --prod

   // 3. Execute the xcode build
    - task: Xcode@5
      inputs:
          actions: 'build'
          xcodeVersion: 'default'
          xcWorkspacePath: '$(system.defaultWorkingDirectory)/ios/App/App.xcworkspace'
          exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
          signingOption: 'manual'
          provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
          packageApp: true
          ...
```

**Output:**

The output from this is that the Xcode@5 task fails with the following output

```
/Users/runner/work/1/s/ios/App/Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig:1:1: error: unable to open file (in target "App" in project "App")
...

##[error]Error: The process '/usr/bin/xcodebuild' failed with exit code 65

```

**Other Information:**

I realise this is a mix of Azure Devops output and yaml, but I was able to get the pipeline working again by settings the specific version of the ionic cli to the following in my Azure Devops yaml file, which suggests its an issue with @ionic/cli@6.20.2

The following script works

```
  - script: |
        sudo npm install -g @ionic/cli@6.20.0
    displayName: 'Install Ionic-CLI'
```

I'll try to see if I can reproduce this issue locally by upgrading to the latest version of the cli and report back with my findings. 

Thanks

**Comment by jcesarmobile** [comment] 2022-10-06 00:23
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4912

**Closed as not planned by jcesarmobile** 2022-10-06 00:23 UTC
Labels: triage
