### ISSUE TITLE
after npm i -D -E @ionic/app-scripts, ionic doesn't start an app

### ISSUE THREAD

**Issue by LucaTrip** [ionic-team/ionic-cli#3827] opened 2019-01-24 12:16 UTC
Hi, I'm having a problem that I can not understand what it's due to. I cloned a project and then I did **ionic serve** in this project. The console presented me an info that I stupidly installed. 

       [INFO] Looks like @ionic/app-scripts isn't installed in this project.
       
       This package is required for this command to work properly. The package provides a CLI 
       utility, but the ionic-app-scripts binary was not found in your PATH.

      ? Install @ionic/app-scripts? Yes
      npm i -D -E @ionic/app-scripts
      npm WARN deprecated babili@0.0.10: babili has been renamed to babel-minify. Please update to 
                  babel-minify
      npm WARN deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please 
                 update to babel-preset-minify

      > node-sass@4.5.0 install /home/trip/workspace/login-screen-demo/node_modules/node-sass
      > node scripts/install.js

      Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64- 
              59_binding.node
      Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/linux-x64- 
             59_binding.node": 

       HTTP error 404 Not Found
 
      Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

      or configure npm proxy via

      npm config set proxy http://example.com:8080

      > node-sass@4.5.0 postinstall /home/trip/workspace/login-screen-demo/node_modules/node-sass
      > node scripts/build.js

      Building: /home/trip/.nvm/versions/node/v9.2.0/bin/node /home/trip/workspace/login-screen- 
              demo/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= -- 
                libsass_cflags= --libsass_ldflags= --libsass_library=
      gyp info it worked if it ends with ok
      gyp verb cli [ '/home/trip/.nvm/versions/node/v9.2.0/bin/node',
      gyp verb cli   '/home/trip/workspace/login-screen-demo/node_modules/node-gyp/bin/node-gyp.js',
      gyp verb cli   'rebuild',
      gyp verb cli   '--verbose',
      gyp verb cli   '--libsass_ext=',
      gyp verb cli   '--libsass_cflags=',
      gyp verb cli   '--libsass_ldflags=',
      gyp verb cli   '--libsass_library=' ]
      gyp info using node-gyp@3.8.0
      gyp info using node@9.2.0 | linux | x64
      gyp verb command rebuild []
      gyp verb command clean []
      gyp verb clean removing "build" directory
      gyp verb command configure []
      gyp verb check python checking for Python executable "python2" in the PATH
      gyp verb `which` succeeded python2 /usr/bin/python2
      gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.12
      gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
      gyp verb get node dir no --target version specified, falling back to host node version: 9.2.0
      gyp verb command install [ '9.2.0' ]
      gyp verb install input version string "9.2.0"
      gyp verb install installing version: 9.2.0
      gyp verb install --ensure was passed, so won't reinstall if already installed
      gyp verb install version is already installed, need to check "installVersion"
      gyp verb got "installVersion" 9
      gyp verb needs "installVersion" 9
      gyp verb install version is good
      gyp verb get node dir target node version installed: 9.2.0
      gyp verb build dir attempting to create "build" dir: /home/trip/workspace/login-screen- 
                demo/node_modules/node-sass/build
      gyp verb build dir "build" dir needed to be created? /home/trip/workspace/login-screen- 
                   demo/node_modules/node-sass/build
      gyp verb build/config.gypi creating config file
      gyp verb build/config.gypi writing out config file: /home/trip/workspace/login-screen- 
                  demo/node_modules/node-sass/build/config.gypi
      gyp verb config.gypi checking for gypi file: /home/trip/workspace/login-screen- 
             demo/node_modules/node-sass/config.gypi
      gyp verb common.gypi checking for gypi file: /home/trip/workspace/login-screen- 
             demo/node_modules/node-sass/common.gypi
      gyp verb gyp gyp format was not specified; forcing "make"
      gyp info spawn /usr/bin/python2
      gyp info spawn args [ '/home/trip/workspace/login-screen-demo/node_modules/node- 
      gyp/gyp/gyp_main.py',
      gyp info spawn args   'binding.gyp',
      gyp info spawn args   '-f',
      gyp info spawn args   'make',
      gyp info spawn args   '-I',
      gyp info spawn args   '/home/trip/workspace/login-screen-demo/node_modules/node- 
                  sass/build/config.gypi',
      gyp info spawn args   '-I',
      gyp info spawn args   '/home/trip/workspace/login-screen-demo/node_modules/node- 
      gyp/addon.gypi',
      gyp info spawn args   '-I',
      gyp info spawn args   '/home/trip/.node-gyp/9.2.0/include/node/common.gypi',
      gyp info spawn args   '-Dlibrary=shared_library',
      gyp info spawn args   '-Dvisibility=default',
      gyp info spawn args   '-Dnode_root_dir=/home/trip/.node-gyp/9.2.0',
      gyp info spawn args   '-Dnode_gyp_dir=/home/trip/workspace/login-screen- 
                demo/node_modules/node-gyp',
      gyp info spawn args   '-Dnode_lib_file=/home/trip/.node-gyp/9.2.0/<(target_arch)/node.lib',
      gyp info spawn args   '-Dmodule_root_dir=/home/trip/workspace/login-screen- 
               demo/node_modules/node-sass',
      gyp info spawn args   '-Dnode_engine=v8',
      gyp info spawn args   '--depth=.',
      gyp info spawn args   '--no-parallel',
      gyp info spawn args   '--generator-output',
      gyp info spawn args   'build',
      gyp info spawn args   '-Goutput_dir=.' ]
      gyp verb command build []
      gyp verb build type Release
      gyp verb architecture x64
      gyp verb node dev dir /home/trip/.node-gyp/9.2.0
      gyp verb `which` succeeded for `make` /usr/bin/make
      gyp info spawn make
      gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
     .... and more lines of g++ compilation....
    @ionic/app-scripts@1.1.3

Now, if I try to create a new project, I'm left with this mistake
       

> Starter template: sidemenu
> ✔ Preparing directory ./testsidemenu - done!
> (node:22046) ExperimentalWarning: The http2 module is an experimental API.
> ⠴ Downloading and extracting sidemenu starter (100.00%) 
> events.js:136
>       throw er; // Unhandled 'error' event
>       ^
>     ZlibError: zlib: Cannot read property 'length' of null
>         at Unzip.Zlib.(anonymous function) (/home/trip/node_modules/minizlib/index.js:126:21)
>         at Unzip.write (/home/trip/node_modules/minizlib/index.js:247:21)
>         at Unzip.flush (/home/trip/node_modules/minizlib/index.js:206:10)
>         at Unzip.end (/home/trip/node_modules/minizlib/index.js:213:10)
>         at Unpack.end (/home/trip/node_modules/tar/lib/parse.js:416:21)
>         at IncomingMessage.onend (_stream_readable.js:598:10)
>         at Object.onceWrapper (events.js:254:19)
>         at IncomingMessage.emit (events.js:164:20)
>         at endReadableNT (_stream_readable.js:1054:12)
>         at _combinedTickCallback (internal/process/next_tick.js:138:11)
> 

I have other ionic projects but doing ionic serves work. I did not understand what I corrupted.

**Comment by dwieeb** [comment] 2019-01-24 21:24
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3816

**Comment by dwieeb** [comment] 2019-01-24 21:25
@LucaTrip Use the latest NodeJS LTS.

**Closed by dwieeb** 2019-01-24 21:24 UTC
Labels: triage

**Comment by LucaTrip** [comment] 2019-01-25 09:39
@dwieeb thanks

**Comment by nestoracv22** [comment] 2019-06-12 14:42
When I create a new project with nativescript I get the same error, 
please I need help

the error:
zlib: Cannot read property 'length' of null

**Comment by jpasiliao** [comment] 2019-07-30 04:21
Im having this kind of erron when using this code  **sudo npm i -g firebase-tools**

any one can share solutiong 
node version 10.16.0
npm version 9.6.0

thanks in advance
