### ISSUE TITLE
Generating platform resources: gets stuck

### ISSUE THREAD

**Issue by cam1708** [ionic-team/ionic-cli#3685] opened 2018-10-09 11:24 UTC
**Description:**
I am unable to generate resources, it just gets stuck at random places

**Steps to Reproduce:**
ionic cordova resources --force

**Output:**
√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
√ Uploading source images to prepare for transformations: 2 / 2 complete - done!
\ Generating platform resources: 7 / 18 complete

**My `ionic info`:**

```
<Ionic:

   ionic (Ionic CLI)  : 4.2.1 (C:\Users\camer\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 4 other plugins)

System:

   NodeJS : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10>
```

**Other Information:**
another issue that sometimes happens:

√ Collecting resource configuration and source images - done!
√ Filtering out image resources that do not need regeneration - done!
Error: read ECONNRESET

    at TLSWrap.onread (net.js:622:25)
- Uploading source images to prepare for transformations

and it just gets stuck here

**Comment by dwieeb** [comment] 2018-10-09 15:18
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3540

**Closed by dwieeb** 2018-10-09 15:18 UTC
Labels: triage
