### ISSUE TITLE
Stuck at ionic cordova resource ios

### ISSUE THREAD

**Issue by Bowman-CN** [ionic-team/ionic-cli#3867] opened 2019-02-16 13:57 UTC
**Description:**

**Steps to Reproduce:**
```shell
ionic cordova resources ios --verbose 
```

**Output:**
```
ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'resources', 'ios' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { configPath: '/Users/XXXX/X-workspace/peek-peak/ionic.config.json', errors: [], context: 'app', type: 'angular' } +0ms
  ionic Context: { binPath: '/Users/XXXX/.nvm/versions/node/v11.9.0/lib/node_modules/ionic/bin/ionic', libPath: '/Users/XXXX/.nvm/versions/node/v11.9.0/lib/node_modules/ionic', execPath: '/Users/XXXX/X-workspace/peek-peak', version: '4.10.3' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: /Users/XXXX/X-workspace/peek-peak/config.xml +0ms
  ionic:lib:integrations:cordova:config Using config.xml: /Users/XXXX/X-workspace/peek-peak/config.xml +21ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova resources' [ 'ios', '--verbose', '--interactive', '--color' ] +0ms
  ionic:commands:cordova:resources imgResources=32 +0ms
  ionic:commands:cordova:resources createImgDestinationDirectories completed: 2 +6ms
  ionic:commands:cordova:resources getSourceImages completed: (./resources/icon.png, ./resources/splash.png) +8ms
  ionic:commands:cordova:resources imgResources=32 +0ms
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
  superagent creating `fs.ReadStream` instance for file: /Users/XXXX/X-workspace/peek-peak/resources/icon.png +0ms
  superagent creating `fs.ReadStream` instance for file: /Users/XXXX/X-workspace/peek-peak/resources/splash.png +1ms
  superagent POST https://res.ionic.io/api/v1/upload +15ms
  superagent setting FormData header: "content-type: multipart/form-data; boundary=--------------------------783911660729796469685198" +1ms
  superagent POST https://res.ionic.io/api/v1/upload +3ms
  superagent setting FormData header: "content-type: multipart/form-data; boundary=--------------------------014437283258974535412800" +1ms
⠙ Uploading source images to prepare for transformations 
  superagent got FormData Content-Length: 64961 +2ms
⠦ Uploading source images to prepare for transformations 
⠼ Uploading source images to prepare for transformations: 1 / 2 complete 
⠴ Uploading source images to prepare for transformations: 2 / 2 complete 
  ionic:commands:cordova:resources uploadSourceImages completed: responses=[ {}, {} ] +3s
  ionic:commands:cordova:resources srcImagesAvailable=[ { ext: '.png',
  ionic:commands:cordova:resources     resType: 'icon',
  ionic:commands:cordova:resources     platform: 'global',
  ionic:commands:cordova:resources     path: '/Users/XXXX/X-workspace/peek-peak/resources/icon.png',
  ionic:commands:cordova:resources     vector: undefined,
  ionic:commands:cordova:resources     height: undefined,
  ionic:commands:cordova:resources     width: undefined,
  ionic:commands:cordova:resources     imageId: '0955f978e2c64cd5c359395c0b07a688' },
  ionic:commands:cordova:resources   { ext: '.png',
  ionic:commands:cordova:resources     resType: 'splash',
  ionic:commands:cordova:resources     platform: 'global',
  ionic:commands:cordova:resources     path:
  ionic:commands:cordova:resources      '/Users/XXXX/X-workspace/peek-peak/resources/splash.png',
  ionic:commands:cordova:resources     vector: undefined,
  ionic:commands:cordova:resources     height: undefined,
  ionic:commands:cordova:resources     width: undefined,
  ionic:commands:cordova:resources     imageId: '4262d34a67a134dbd69690643604a0d8' } ] +0ms
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon.png-e3bd9a +0ms
  superagent POST https://res.ionic.io/api/v1/transform +23ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon@2x.png-81b85f +3ms
  superagent POST https://res.ionic.io/api/v1/transform +2ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-40.png-db5f2d +1ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-40@2x.png-416986 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-40@3x.png-d58c3d +0ms
  superagent POST https://res.ionic.io/api/v1/transform +12ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-50.png-a40aea +12ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-50@2x.png-9a6b6d +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-60.png-a79a27 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-60@2x.png-c06a9f +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-60@3x.png-5aeef2 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +12ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-72.png-e28e34 +12ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-72@2x.png-14a281 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-76.png-aedccc +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-76@2x.png-603d3d +1ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-83.5@2x.png-91803e +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-small.png-901257 +2ms
  superagent POST https://res.ionic.io/api/v1/transform +2ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-small@2x.png-447363 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-small@3x.png-4df9e3 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-icon-1024.png-465647 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +11ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-568h@2x~iphone.png-68168e +11ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-667h.png-f6f8c0 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-736h.png-452c88 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Landscape-736h.png-f98799 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Landscape@2x~ipad.png-893dbe +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Landscape@~ipadpro.png-84c5b8 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Landscape~ipad.png-b58083 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Portrait@2x~ipad.png-891059 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Portrait@~ipadpro.png-0d0565 +12ms
  superagent POST https://res.ionic.io/api/v1/transform +11ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default-Portrait~ipad.png-7036e0 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default@2x~iphone.png-fc2343 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default~iphone.png-0e9ac1 +0ms
  superagent POST https://res.ionic.io/api/v1/transform +1ms
  ionic:lib:integrations:cordova:resources creating write stream for tmp file: /var/folders/31/0h58m3pn67x8nr08mqb119680000gy/T/ionic-cordova-resources-Default@2x~universal~anyany.png-ba23d7 +1ms
  superagent POST https://res.ionic.io/api/v1/transform +0ms
⠸ Generating platform resources 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +1s
⠦ Generating platform resources 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +133ms
⠧ Generating platform resources 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +90ms
⠸ Generating platform resources: 2 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +182ms
  ionic:lib:integrations:cordova:resources response 200 received for icon-83.5@2x.png: (id: 0955f978e2c64cd5c359395c0b07a688) +182ms
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +11ms
⠇ Generating platform resources: 4 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +138ms
⠏ Generating platform resources: 4 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +85ms
⠧ Generating platform resources: 7 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +257ms
⠹ Generating platform resources: 8 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +205ms
⠼ Generating platform resources: 9 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +41ms
⠴ Generating platform resources: 9 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +70ms
⠧ Generating platform resources: 10 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +24ms
⠼ Generating platform resources: 12 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +296ms
⠴ Generating platform resources: 12 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +38ms
⠇ Generating platform resources: 12 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +144ms
  ionic:lib:integrations:cordova:resources response 200 received for Default-Portrait~ipad.png: (id: 4262d34a67a134dbd69690643604a0d8) +144ms
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +27ms
⠙ Generating platform resources: 13 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +69ms
⠋ Generating platform resources: 17 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +299ms
⠙ Generating platform resources: 17 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +25ms
⠼ Generating platform resources: 18 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +111ms
⠇ Generating platform resources: 19 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +164ms
⠏ Generating platform resources: 19 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +27ms
⠹ Generating platform resources: 20 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +89ms
⠸ Generating platform resources: 20 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +74ms
⠸ Generating platform resources: 24 / 32 complete 
  superagent POST https://res.ionic.io/api/v1/transform -> 200 +305ms
⠙ Generating platform resources: 25 / 32 complete 
```

**My `ionic info`:**

```
ionic --version : 4.10.3
cordova --version: 8.1.2 (cordova-lib@8.1.1)
```

**Other Information:**

**Comment by dwieeb** [comment] 2019-02-16 21:05
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3540

**Closed by dwieeb** 2019-02-16 21:05 UTC
Labels: triage
