### ISSUE TITLE
ionic-v1[1268]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfov8::Value &): Assertion `args[1]->IsString()' failed.

### ISSUE THREAD

**Issue by digitalfractal** [ionic-team/ionic-cli#3790] opened 2018-12-11 23:23 UTC
**Description:**
trying to run an ionic 1 project build on mac command line and build a new xcode project

**Steps to Reproduce:**

running ionic cordova build ios 

**Output:**
> ionic-v1 build
ionic-v1[1268]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x10003ae75 node::Abort() [/usr/local/bin/node]
 2: 0x100039ed3 node::AddEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/usr/local/bin/node]
 3: 0x1000649b7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x10023036f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x10022f50b v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x10022ef27 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x2af160edbe3d 
 8: 0x2af160e8d145 
 9: 0x2af160f0b87d 
10: 0x2af160e918d5 
11: 0x2af160e918d5 
12: 0x2af160e918d5 
[ERROR] Non-zero exit from subprocess.

**My `ionic info`:**

Ionic:

   ionic (Ionic CLI) : 4.3.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 1.0.14

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.2.3, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.1.1, (and 8 other plugins)

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS High Sierra
   Xcode  : Xcode 10.1 Build version 10B61

**Other Information:**

**Comment by dwieeb** [comment] 2018-12-13 03:56
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3462

**Comment by dwieeb** [comment] 2018-12-13 03:56
Fix is here: https://github.com/ionic-team/ionic-cli/issues/3462

Let me know if it doesn't work.

**Closed by dwieeb** 2018-12-13 03:56 UTC
Labels: triage

**Comment by digitalfractal** [comment] 2018-12-13 20:04
Hi

I followed all commands and still get the same non-zero exit from subprocess

ionic cordova build ios

> ionic-v1 build

ionic-v1[16095]: ../src/node_contextify.cc:628:static void
node::contextify::ContextifyScript::New(const
FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.

 1: 0x10003ae75 node::Abort() [/usr/local/bin/node]

 2: 0x100039ed3 node::AddEnvironmentCleanupHook(v8::Isolate*, void
(*)(void*), void*) [/usr/local/bin/node]

 3: 0x1000649b7
node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value>
const&) [/usr/local/bin/node]

 4: 0x10023036f
v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*)
[/usr/local/bin/node]

 5: 0x10022f50b v8::internal::MaybeHandle<v8::internal::Object>
v8::internal::(anonymous
namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*,
v8::internal::Handle<v8::internal::HeapObject>,
v8::internal::Handle<v8::internal::HeapObject>,
v8::internal::Handle<v8::internal::FunctionTemplateInfo>,
v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)
[/usr/local/bin/node]

 6: 0x10022ef27
v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments,
v8::internal::Isolate*) [/usr/local/bin/node]

 7: 0x19edb78dbe3d

 8: 0x19edb788d145

 9: 0x19edb790b87d

10: 0x19edb78918d5

11: 0x19edb78918d5

12: 0x19edb78918d5

[*ERROR*] Non-zero exit from subprocess.


my xcode is Version 10.1 (10B61)

**Comment by dwieeb** [comment] 2018-12-13 20:59
@digitalfractal Try updating your Node version to latest 10?

**Comment by digitalfractal** [comment] 2018-12-13 21:10
i installed the latest v10

here is the info


*Ionic:*


   ionic (Ionic CLI) : 4.3.1 (/usr/local/lib/node_modules/ionic)

   Ionic Framework   : ionic1 1.3.4

   @ionic/v1-toolkit : 1.0.14


*Cordova:*


   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)

   Cordova Platforms     : android 6.2.3, ios 4.5.5

   Cordova Plugins       : cordova-plugin-ionic-webview 1.1.1, (and 8 other
plugins)


*System:*


   NodeJS : v10.14.2 (/usr/local/bin/node)

   npm    : 6.4.1

   OS     : macOS High Sierra

   Xcode  : Xcode 10.1 Build version 10B61


still i get this output


> ionic-v1 build

ionic-v1[16319]: ../src/node_contextify.cc:633:static void
node::contextify::ContextifyScript::New(const
FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.

 1: 0x10003b125 node::Abort() [/usr/local/bin/node]

 2: 0x10003a183 node::AddEnvironmentCleanupHook(v8::Isolate*, void
(*)(void*), void*) [/usr/local/bin/node]

 3: 0x100064bc1
node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value>
const&) [/usr/local/bin/node]

 4: 0x10023122f
v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*)
[/usr/local/bin/node]

 5: 0x1002303cb v8::internal::MaybeHandle<v8::internal::Object>
v8::internal::(anonymous
namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*,
v8::internal::Handle<v8::internal::HeapObject>,
v8::internal::Handle<v8::internal::HeapObject>,
v8::internal::Handle<v8::internal::FunctionTemplateInfo>,
v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)
[/usr/local/bin/node]

 6: 0x10022fde7
v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments,
v8::internal::Isolate*) [/usr/local/bin/node]

 7: 0xc06e145be3d

 8: 0xc06e140d145

 9: 0xc06e148ba7d

10: 0xc06e14118d5

11: 0xc06e14118d5

12: 0xc06e14118d5

[*ERROR*] Non-zero exit from subprocess.

**Comment by digitalfractal** [comment] 2018-12-22 05:56
installed the latest 10.14.2 version of node on a different machine and try
to run the ionic cordova build ios and get the following error

ionic-v1 build

ionic-v1[3667]: ../src/node_contextify.cc:633:static void
node::contextify::ContextifyScript::New(const
FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.

 1: 0x10003b125 node::Abort() [/usr/local/bin/node]

 2: 0x10003a183 node::AddEnvironmentCleanupHook(v8::Isolate*, void
(*)(void*), void*) [/usr/local/bin/node]

 3: 0x100064bc1
node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value>
const&) [/usr/local/bin/node]

 4: 0x10023122f
v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*)
[/usr/local/bin/node]

 5: 0x1002303cb v8::internal::MaybeHandle<v8::internal::Object>
v8::internal::(anonymous
namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*,
v8::internal::Handle<v8::internal::HeapObject>,
v8::internal::Handle<v8::internal::HeapObject>,
v8::internal::Handle<v8::internal::FunctionTemplateInfo>,
v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)
[/usr/local/bin/node]

 6: 0x10022fde7
v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments,
v8::internal::Isolate*) [/usr/local/bin/node]

 7: 0x3431490dbe3d

 8: 0x34314908d145

 9: 0x34314910ba7d

10: 0x3431490918d5

11: 0x3431490918d5

12: 0x3431490918d5

[*ERROR*] Signal exit from subprocess.
