### ISSUE TITLE
ionic cap run electron throws error

### ISSUE THREAD

**Issue by NiklasMerz** [ionic-team/ionic-cli#3871] opened 2019-02-20 21:28 UTC
**Description:**

Building for capacitor electron throws an error,
Probably this wants to start the native IDE for electron which is not needed. I expected it to run `npm run electron:start` in the electron folder. 

**Steps to Reproduce:**

`ionic cap run electron` on project with capacitor initialized for electron throws error:

**Output:**

```
> capacitor copy electron
⠋ Copying web assets from www to electron/appCleaning /home/niklas/Projekte/exportoo/electron/app...
Copying web assets...
✔ Copying web assets from www to electron/app in 324.87ms
✔ Copying capacitor.config.json in 531.53μp
✔ copy in 327.81ms

[INFO] Ready for use in your Native IDE!
       
       To continue, run your project on a device or emulator using Android Studio!

> capacitor open electron
[error] Platform electron is not valid.
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor open electron exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

**My `ionic info`:**

```
Capacitor version:
beta 17
node version:
10.10
npm version:
6.7
```

**Comment by dwieeb** [comment] 2020-02-05 04:08
Yeah, we shouldn't call `capacitor open` for Electron. 

We should probably have a warning here that Electron support is beta in Ionic (along with cleaning up the Android Studio messages). See my comment here: https://github.com/ionic-team/ionic-cli/pull/4254#issuecomment-567247499

**Comment by jcesarmobile** [comment] 2020-05-20 12:21
this was a capacitor "issue", it didn't have open command for electron, but it does now, so the reported issue can't be reproduced

the app will still not work since electron apps are served from file protocol and that needs some extra steps depending on the framework, like configuring the basehref for angular or the homepage for react, but that's a different topic, so closing this issue.

**Closed by jcesarmobile** 2020-05-20 12:21 UTC
Labels: bug, capacitor
