### ISSUE TITLE
Freeze on splashscreen with loading icon on iOS device

### ISSUE THREAD

**Issue by Borongaj** [ionic-team/ionic-cli#4055] opened 2019-06-27 20:19 UTC
**Version:**

native-run  : 0.2.7

**Description:**
From CLI, `ionic cordova run ios -l --consolelogs`:

Starts the app on device, but freeze on splashscreen with loading icon.

From Xcode, running the app on device : **Works perfectly**.

**Command Output:**

[native-run] 2019-06-27T20:06:33.583Z protocol:usbmux Response: {"MessageType":"Result","Number":0}
[native-run] 2019-06-27T20:06:33.583Z client:lockdownd getAllValues
[native-run] 2019-06-27T20:06:33.583Z protocol:lockdown socket write: {"Request":"GetValue"}
[native-run] 2019-06-27T20:06:33.722Z protocol:lockdown Response: {"Request":"GetValue","Value":{"DeviceName":"iPhone","HardwareModel":"N841AP","ProductName":"iPhone OS","ProductType":"iPhone11,8","ProductVersion":"12.3"}}
[native-run] 2019-06-27T20:06:33.723Z client:usbmuxd connectUsbmuxdSocket
[native-run] 2019-06-27T20:06:33.723Z client:usbmuxd getDevice udid: 00008020-000169E914D1002E
[native-run] 2019-06-27T20:06:33.723Z client:usbmuxd getDevices
[native-run] 2019-06-27T20:06:33.723Z protocol:usbmux socket write: {"messageType":"ListDevices"}
[native-run] 2019-06-27T20:06:33.725Z protocol:usbmux Response: {"DeviceList":[{"DeviceID":3824,"MessageType":"Attached","Properties":{"ConnectionSpeed":480000000,"ConnectionType":"USB","DeviceID":3824,"LocationID":337772544,"ProductID":4776,"SerialNumber":"00008020-000169E914D1002E"}},{"DeviceID":3823,"MessageType":"Attached","Properties":{"ConnectionType":"Network","DeviceID":3823,"EscapedFullServiceName":"dc:08:0f:2f:a8:59@fe80::de08:fff:fe2f:a859._apple-mobdev2._tcp.local.","InterfaceIndex":5,"NetworkAddress":{"type":"Buffer","data":[16,2,0,0,192,168,1,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"SerialNumber":"00008020-000169E914D1002E"}}]}
[native-run] 2019-06-27T20:06:33.725Z client:usbmuxd readPairRecord: 00008020-000169E914D1002E
[native-run] 2019-06-27T20:06:33.725Z protocol:usbmux socket write: {"messageType":"ReadPairRecord","extraFields":{"PairRecordID":"00008020-000169E914D1002E"}}

**Environment Info:**

Ionic:

   Ionic CLI                     : 5.2.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.10.7
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.3.1, (and 12 other plugins)

Utility:

   cordova-res : 0.5.1 
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/Users/laurentgleizes/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v11.9.0 (/usr/local/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

macOS version: 10.14.5

Xcode version: 10.2.1

**Comment by dwieeb** [comment] 2019-06-27 20:50
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4047

**Comment by dwieeb** [comment] 2019-06-27 20:50
@Borongaj You need to add `--address=0.0.0.0`. Here are the docs on livereload: https://ionicframework.com/docs/building/ios#running-with-the-ionic-cli

**Closed by dwieeb** 2019-06-27 20:50 UTC
Labels: triage
