### ISSUE TITLE
ionic serve faild - error:Error:EPERM:operation not permitted

### ISSUE THREAD

**Issue by Davidlala** [ionic-team/ionic-cli#1071] opened 2016-06-13 12:16 UTC
![capture](https://cloud.githubusercontent.com/assets/7421616/16007206/bae07db8-3179-11e6-9628-65303f5397a8.PNG)

**Comment by Mobius77x** [comment] 2016-06-14 02:47
If you're on Windows try running your Command Prompt as an Administrator (right-click and choose Run as Administrator). This will then give you the permission to create directories.

**Comment by Davidlala** [comment] 2016-06-14 07:53
thanks for reply,  still the same error

**Comment by derksacklowski** [comment] 2016-06-21 16:49
having the same error

**Comment by saurabhvyas** [comment] 2016-07-10 03:47
me too

**Comment by Mobius77x** [comment] 2016-08-17 04:18
Unfortunately I'm experiencing EPERM issues again after a period of it working when running as Administrator.  Argh! Have tried turning of Anti-Virus, backup software etc that may also be accessing the files to no success.

Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS: Windows 8.1
Node Version: v5.11.0

**Comment by derksacklowski** [comment] 2016-08-17 07:08
My problem was atom.io locking some files. Closing and reopening the editor solved it for me. Maybe this is somewhat related?

**Comment by Mobius77x** [comment] 2016-08-17 09:05
@derksacklowski Thanks for that suggestion but I already tried that without success. I am using Visual Studio Code.  I just had a thought that it could be an extension I'm using with that though. When I find the cause I'll re-post...

**Closed** 2018-07-12 17:55 UTC
Labels: ionitron: old major version
