### ISSUE TITLE
Can't start a new project (Error 405)

### ISSUE THREAD

**Issue by joelreyna1104** [ionic-team/ionic-cli#4105] opened 2019-07-31 22:00 UTC
**Description:**

When I try to create a new project I always get the same error

> Error: Encountered bad status code (405) for https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-blank.tar.gz
> 
> This could mean the server is experiencing difficulties right now--please try again later.
> at Request.req.on.res (C:\Users\Xbox 1\AppData\Roaming\npm\node_modules\ionic\lib\utils\http.js:64:24)
> at Request.emit (events.js:198:13)
> at Request._emitResponse (C:\Users\Xbox
> 1\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:862:8)
> at ClientRequest.req.once.res (C:\Users\Xbox
> 1\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent\lib\node\index.js:412:10)
> at Object.onceWrapper (events.js:286:20)
> at ClientRequest.emit (events.js:203:15)
> at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
> at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
> at Socket.socketOnData (_http_client.js:442:20)

That same behaviour occurs when I try to integrate cordova to the application for installing plugins

**Other Information:**

Ionic-cli version: 5.2.3

**Comment by dwieeb** [comment] 2019-07-31 22:12
This is likely a duplicate of https://github.com/ionic-team/ionic-cli/issues/3987

You likely need to configure your environment for your network proxy:

* Please carefully follow the docs: https://ionicframework.com/docs/cli/using-a-proxy
* Your organization needs to provide proxy details for you. If you don't know the details, talk with your network administrator.
* Remember to avoid disabling SSL verification. This can lead to prolonged insecure configuration with your computer.

**Closed by dwieeb** 2019-07-31 22:12 UTC
Labels: triage

**Comment by joelreyna1104** [comment] 2019-07-31 22:34
I do not understand what do you mean with my network proxy. My computer is not using any organizations proxy (it is a personal network at home). I just installed ionic like I did in my laptop but is is not working on my PC.

**Comment by dwieeb** [comment] 2019-08-01 16:07
It may not be a proxy issue--it's difficult to tell with these network errors.

I just successfully ran `ionic start`, but it could mean the cloudfront servers in your region are having issues. Is this still an issue today?

**Comment by joelreyna1104** [comment] 2019-08-04 06:01
Yes, the issue is still present.

**Comment by RyanAntenor** [comment] 2019-08-05 02:05
Same here:
```
Error: Encountered bad status code (400) for https://d2ql0qc7j8u4b2.cloudfront.net/angular-official-sidemenu.tar.gz

This could mean the server is experiencing difficulties right now--please try again later.

```
I'm also running on my personal network and not running in a proxy. Can we reopen this issue ?

My current version: ionic@5.2.3

**Comment by RyanAntenor** [comment] 2019-08-05 02:32
Hi, I figured out the problem . It seems on that I have setup a proxy long time ago. 
so what you need to do is to unset the proxy if you are not using it. 

Try using like this:
`ionic config unset -g proxy`

**Comment by RyanAntenor** [comment] 2019-08-05 02:34
> Yes, the issue is still present.

Try unset the proxy if you not using it:
`ionic config unset -g proxy`

**Comment by joelreyna1104** [comment] 2019-08-05 16:28
That solved the problem for me too, thanks!

**Comment by Boby** [comment] 2019-11-19 20:22
turns out @RyanAntenor solutions works!!
