### ISSUE TITLE
 Ionic v4 white screen and android icons

### ISSUE THREAD

**Issue by deniscesar** [ionic-team/ionic-cli#3684] opened 2018-10-08 12:41 UTC
**Description:**
I have some problems that I would like to know more.

1- It seems to be an angular routing error when running APP on real Android device

2- Icons In the browser shows, but the device android does not show.

**Steps to Reproduce:**

```
ionic cordova run android
```

**Output 1:**

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
runtime.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
styles.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
cordova.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vendor.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Output 2:**

```
Fetch API cannot load file:///android_asset/www/svg/md-information-circle.svg. URL scheme "file" is not supported.
```

**My `ionic info`:**

```
Ionic cli: 4.2.1
cordova-plugin-ionic-webview: 2.2.0
cordova-android: 6.3.0
```

**Other Information:**
Some say to modify from 
```<base href = "/" /> ``` to ``` <base href = "./" />```
I wonder if this is right or is it a bug?
Are cli or webview problems?

**Comment by dwieeb** [comment] 2018-10-08 14:57
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3530

**Closed by dwieeb** 2018-10-08 14:57 UTC
Labels: triage
