### ISSUE TITLE
CLI hangs at "[INFO] Waiting for connectivity with ionic-app-scripts..."

### ISSUE THREAD

**Issue by jwt02180** [ionic-team/ionic-cli#3483] opened 2018-08-06 13:27 UTC
**Description:**
With the latest app-scripts and CLI, running `ionic serve` hangs and repeatedly displays "Waiting for connectivity with ionic-app-scripts...".

I've found that running the command `ionic serve --address 127.0.0.1` resolves this issue.

Looking at a recent [commit](https://github.com/ionic-team/ionic-cli/commit/12c3f353dda789016c584310b5129258dc06fb17) to the CLI repo it seems that this has attempted to be fixed, but for me the issue remains unless I provide the address.

**Steps to Reproduce:**
Run `ionic serve` with latest CLI and app-scripts.

**Output:**
_excerpt from running `ionic serve --verbose`_
```
[app-scripts] [09:25:20]  clean started ...
[app-scripts] [09:25:20]  clean finished in 3 ms
[app-scripts] [09:25:20]  copy started ...
[app-scripts] [09:25:21]  deeplinks started ...
[app-scripts] [09:25:21]  deeplinks finished in 584 ms
[app-scripts] [09:25:21]  transpile started ...
[app-scripts] [09:25:29]  transpile finished in 7.67 s
[app-scripts] [09:25:29]  preprocess started ...
[app-scripts] [09:25:29]  preprocess finished in less than 1 ms
[app-scripts] [09:25:29]  webpack started ...
[app-scripts] [09:25:29]  copy finished in 8.57 s
[app-scripts] [09:25:37]  webpack finished in 8.25 s
[app-scripts] [09:25:37]  sass started ...
[app-scripts] Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
[app-scripts] [09:25:39]  sass finished in 2.08 s
[app-scripts] [09:25:39]  postprocess started ...
[app-scripts] [09:25:39]  postprocess finished in 16 ms
[app-scripts] [09:25:39]  lint started ...
[app-scripts] [09:25:39]  build dev finished in 18.96 s
[app-scripts] [09:25:40]  watch ready in 19.61 s
  ionic:cli-utils:lib:serve awaiting TCP connection to 0.0.0.0:8103 +0ms
[INFO] Waiting for connectivity with ionic-app-scripts...
[app-scripts] [09:25:47]  lint finished in 7.54 s
[INFO] Waiting for connectivity with ionic-app-scripts...
[INFO] Waiting for connectivity with ionic-app-scripts...
```

**My `ionic info`:**
```
Ionic:

   ionic (Ionic CLI)  : 4.0.3 (C:\nvm\v8.9.0\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

System:

   NodeJS : v8.9.0 (C:\Program Files\nodejs\node.exe)
   npm    : 5.5.1
   OS     : Windows 10
```

**Other Information:**
Looks like this is similar to #3410

**Comment by dwieeb** [comment] 2018-08-06 18:05
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3410

**Comment by dwieeb** [comment] 2018-08-06 18:05
The fix is not yet released.

**Closed by dwieeb** 2018-08-06 18:05 UTC
Labels: triage
