### ISSUE TITLE
Error: TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by MustafaMohamed2018** [ionic-team/ionic-cli#4544] opened 2020-09-05 22:14 UTC
**Description:**

**Steps to Reproduce:**
ionic start myApp blank --cordova --confirm

**Output:**
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\warn-mixin.js:19:40)
    at Unpack.warn (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\unpack.js:188:18)
    at Unpack.<anonymous> (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:82:14)
    at Unpack.emit (events.js:326:22)
    at Unpack.[emit] (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:286:12)
    at Unpack.[maybeEnd] (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:402:17)
    at Unpack.[consumeChunk] (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:434:21)
    at Unpack.write (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:365:25)
    at Unpack.end (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:479:14)
    at IncomingMessage.onend (_stream_readable.js:678:10)
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (_stream_readable.js:754:14)
    at Unpack.emit (events.js:314:20)
    at Unpack.warn (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\warn-mixin.js:19:12)
    at Unpack.warn (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\unpack.js:188:18)
    [... lines matching original stack trace ...]
    at Unpack.write (C:\Users\UserX\AppData\Roaming\npm\node_modules\@ionic\cli\node_modules\tar\lib\parse.js:365:25) {
  recoverable: false,
  cwd: 'G:\\My Projects\\gulf-wallet',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}

**My `ionic info`:**

```
ionic 6.11.8
```

**Other Information:**

node v 14.9.0

**Comment by imhoffd** [comment] 2020-09-08 15:07
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4454

**Closed as completed by imhoffd** 2020-09-08 15:07 UTC
Labels: triage
