### ISSUE TITLE
Unable to install ionic "404 Not Found: @ionic/cli-framework@1.0.7" and 404 Not Found: @ionic/utils-fs@0.0.1

### ISSUE THREAD

**Issue by steven-ponessa** [ionic-team/ionic-cli#3656] opened 2018-10-02 01:31 UTC
Cannot install ionic and cordova on a clean system.
Running npm install -g ionic cordova results in:
`404 Not Found: @ionic/cli-framework@1.0.7`

Node version: v9.5.0
NPM version: 6.4.0

Steps to Reproduce

`sudo npm install -g ionic cordova`

**Comment by dwieeb** [comment] 2018-10-02 16:16
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3562

Can you try what I wrote in the comment?

**Comment by steven-ponessa** [comment] 2018-11-15 13:58
Same here, neither moving to a more current version of Node/NPM than in the
original bug or clearing the NPM cache worked.  I am currently running Node
9.5.0 and NPM 6.4.0.

Stevens-MacBook-Pro:_logs steve$ npm install -g cordova ionic

npm ERR! code E404

npm ERR! 404 Not Found: @ionic/cli-framework@1.3.0


npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/steve/.npm/_logs/2018-11-15T13_53_51_571Z-debug.log

Stevens-MacBook-Pro:_logs steve$ node -v

v9.5.0

Stevens-MacBook-Pro:_logs steve$ npm -v

6.4.0

**Comment by loganfromlogan** [comment] 2018-11-15 16:12
Looks like my problem was actually a broken npm registry setting. Running `npm config set registry https://registry.npmjs.org/` fixed it for me.

**Comment by steven-ponessa** [comment] 2018-11-15 20:18
Tried `npm config set registry https://registry.npmjs.org/`, without knowing what that would do, however still getting the `404 Not Found: @ionic/cli-framework@1.3.0`

**Comment by MelB-tran** [comment] 2018-11-19 03:31
which is this issue closed? it's clearly not resolved for folks. I cannot find anything online that fixes this. I've made sure to uninstall previous ionic versions and my node v is `10.13.0` and npm v is `6.4.1.` I keep getting the following error `Not Found: @ionic/cli-framework@1.3.0`

**Comment by dwieeb** [comment] 2018-11-19 17:31
@MelB-tran This issue is not closed.

Here are my troubleshooting steps for this issue:

* Try setting the registry explicitly: `npm config set registry https://registry.npmjs.org/`
* Try `npm cache clean -f`
* Try fully uninstalling NodeJS and installing the latest versions of NodeJS and npm.
* Make sure you aren't using a proxy or other network configurations that may interfere with your access to `https://registry.npmjs.org` on the command line. These settings could be misconfigured in your terminal program, your computer, or your network. If you are in an organization, talk to your network administrator.

**Comment by MelB-tran** [comment] 2018-11-19 17:49
My mistake! I've tried all of these but the last one, I will give it a shot, thanks 

> 
> 
> @MelB-tran This issue is not closed.
> 
> Here are my troubleshooting steps for this issue:
> 
>     * Try setting the registry explicitly: `npm config set registry https://registry.npmjs.org/`
> 
>     * Try `npm cache clean -f`
> 
>     * Try fully uninstalling NodeJS and installing the latest versions of NodeJS and npm.
> 
>     * Make sure you aren't using a proxy or other network configurations that may interfere with your access to `https://registry.npmjs.org` on the command line. These settings could be misconfigured in your terminal program, your computer, or your network. If you are in an organization, talk to your network administrator.

**Comment by steven-ponessa** [comment] 2018-11-19 17:55
Same
```
npm install -g ionic cordova
npm ERR! code E404
npm ERR! 404 Not Found: @ionic/cli-framework@1.3.0
```

**Comment by dwieeb** [comment] 2018-11-19 19:00
@steven-ponessa Make sure you aren't using a proxy or other network configurations that may interfere with your access to `https://registry.npmjs.org` on the command line. These settings could be misconfigured in your terminal program, your computer, or your network. If you are in an organization, talk to your network administrator.

**Comment by dwieeb** [comment] 2018-11-19 19:01
For those behind a network proxy, we have some docs on proxying requests here: https://beta.ionicframework.com/docs/cli/using-a-proxy#other-clis

Each CLI that you use must be configured separately to proxy network requests.

**Comment by dwieeb** [comment] 2018-11-30 23:03
@MelB-tran @steven-ponessa Any luck?

**Comment by MelB-tran** [comment] 2018-12-01 03:40
I uninstalled npm completely and reinstalled usinng homebrew. Then tried installing using “npm install -g ionic” and it installed fine

**Closed** 2019-05-22 22:12 UTC
Labels: triage
