### ISSUE TITLE
[ERROR] Could not parse build output file:         APP_Folder/platforms/android/app/build/outputs/apk/debug/output.json

### ISSUE THREAD

**Issue by mashithalalodya** [ionic-team/ionic-cli#4484] opened 2020-07-12 02:10 UTC
Description:

My app was working Build, error says "Could not parse build output file:         APP_Folder/platforms/android/app/build/outputs/apk/debug/output.json". How to solve that problem

Steps to Reproduce:

Run sudo ionic cordova run android

**Output:**
BUILD SUCCESSFUL

Total time: 10.255 secs
Built the following apk(s): 
	APP_FOLDER/platforms/android/build/outputs/apk/android-debug.apk
[ERROR] Could not parse build output file:
       APP_FOLDER/platforms/android/app/build/outputs/apk/debug/output.json

**Ionic info**
Ionic:

   Ionic CLI                     : 6.4.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 7.1.0
   Cordova Platforms : android 6.3.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.0.0) : 0.2.8

System:

   Android SDK Tools : 26.1.1 (//Library/Android/sdk)
   NodeJS            : v12.17.0 (/usr/local/bin/node)
   npm               : 6.14.4
   OS                : macOS Catalina

**Comment by imhoffd** [comment] 2020-07-13 16:04
Duplicate of https://github.com/ionic-team/ionic-cli/issues/4467

**Closed as completed by imhoffd** 2020-07-13 16:04 UTC
Labels: triage
