### ISSUE TITLE
ionic state reset : Caught exception:  undefined

### ISSUE THREAD

**Issue by crouti** [ionic-team/ionic-cli#1673] opened 2016-11-14 13:46 UTC
`ionic state reset`

outputs:

```
Removed platforms and plugins
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add android
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-device
Caught exception:
 undefined 
```

Mind letting us know? https://github.com/driftyco/ionic-cli/issues

my config is:
```
Your system information:

Cordova CLI: 6.4.0 
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: OS X El Capitan
Node Version: v5.2.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by fernandoluizao** [comment] 2016-11-15 21:57
Same here...

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.39
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.1.0
Xcode version: Not installed
```

The problem is with ionic-app-lib. Upgrading to 2.1.5 solves the problem. 

Looks like its already fixed by https://github.com/driftyco/ionic-cli/commit/9667f3d211b08478f28418b400f57bd40eada8d4, but it's not released on npm yet.

**Comment by fernandoluizao** [comment] 2016-11-17 12:35
I was wrong about ionic-app-lib... 

I have another project with the exact versions of my previous "ionic info", except that this project was generated with a beta version of Ionic, and upgraded to 2.0.0-rc.2 later, and everything works.

With a fresh project, the problem appears.

So I think the issue is with some dependency version. I tried to diff node_modules on both projects, but can't figure out what was wrong.

Hope this helps to bissect the problem.

**Comment by vjanssens** [comment] 2016-11-25 09:51
I'm having the same issue after a `ionic state restore` (closed my own issue #1723 after seeing this one).

Putting the gist of my issue below:

```
$ ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add ios

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist
Caught exception:
undefined

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

#### What behavior are you expecting?
Normal ionic state restore command (adding platforms and plugins from package.json)

**Steps to reproduce:**
1. `$ ionic state restore`

```
package.json
{
  "name": "app",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  },
  "cordovaPlugins": [
    "cordova-plugin-whitelist",
    "cordova-plugin-statusbar",
    "cordova-plugin-console",
    "cordova-plugin-device",
    "cordova-plugin-splashscreen",
    "ionic-plugin-keyboard",
    "cordova-plugin-network-information",
    "cordova-plugin-file-transfer",
    "cordova-plugin-file"
  ],
  "cordovaPlatforms": [
    "ios",
    {
      "platform": "ios",
      "version": "",
      "locator": "ios"
    }
  ],
  "description": "An Ionic project"
}
```

**Post the output of `ionic info` below please**
```
Your system information:

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0
ios-sim version: 5.0.11
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by fernandoluizao** [comment] 2016-11-25 10:01
Maybe _ionic state_ is going to [disappear](https://github.com/driftyco/ionic-cli/issues/1324)?

**Comment by abennouna** [comment] 2016-12-29 13:00
[sorry for the long comment, feel free to edit it if helps]

When I have such issues, they are generally related to Android SDK Components.

Just to confirm, I have exactly the same output on an previously working environment:
```
$ ionic state restore
Attempting to restore your Ionic application from package.json

Restoring Platforms

cordova platform add ios
cordova platform add android

Restore platforms is complete

Restoring Plugins

cordova plugin add cordova-plugin-whitelist
Caught exception:
 undefined 

Mind letting us know? https://github.com/driftyco/ionic-cli/issues
```

with the following environment:
```
$ ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 0.0.48
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.2.1 Build version 8C1002
```

With that error, I tried to install a plugin directly and I got the real error:
```
$ ionic plugin add cordova-plugin-crosswalk-webview
Installing "cordova-plugin-crosswalk-webview" for android


ANDROID_HOME=/Users/abdelaziz/Library/android-sdk-macosx

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home

Subproject Path: CordovaLib



FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 25].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.

  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html


* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug
 option to get more log output.


BUILD FAILED

Total time: 2.764 secs


Failed to install 'cordova-plugin-crosswalk-webview':Error: /pathToApp/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/pathToApp/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)


Error: /pathToApp/platforms/android/gradlew: Command failed with exit code 1
```

The reason was that I updated to cordova-android@6.1.0 but I haven't installed the required Android SDK Components.

Another time, it was a similar Android SDK missing component that I must have deleted by mistake:
```
$ ionic plugin add cordova-plugin-whitelist
Installing "cordova-plugin-whitelist" for android


ANDROID_HOME=/Users/abdelaziz/Library/android-sdk-macosx

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home

Subproject Path: CordovaLib

Incremental java compilation is an incubating feature.




FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:
  [Android Support Repository].

  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html


* Try:
Run with --stacktrace option to get the stack trace. Run with 
--info or --debug option to get more log output.



BUILD FAILED



Total time: 2.007 secs

Failed to install 'cordova-plugin-whitelist':Error: /pathToApp/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/pathToApp/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)


Error: /pathToApp/platforms/android/gradlew: Command failed with exit code 1
```

So my suggestion is: _as long as ionic-cli doesn't return debug info from cordova_, you can check whether the real error is related to Android SDK by running ```ionic plugin add cordova-plugin-whitelist``` for instance.

Also, updating cordova platform through ionic-cli gives the same kind of debug info:
```
ionic platform add android@latest
Adding android project...


Creating Cordova project for the Android platform:

	Path: platforms/android
	Package: com.ionicframework.prototype161448


	Name: Prototype_Sicareme
	Activity: MainActivity
	Android target: android-25

Subproject Path: CordovaLib

Android project created with cordova-android@6.1.0

Installing "cordova-plugin-android-fingerprint-auth" for android

ANDROID_HOME=/Users/abdelaziz/Library/android-sdk-macosx

JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home

Subproject Path: CordovaLib


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> You have not accepted the license agreements of the following SDK components:

  [Android SDK Platform 25].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED


Total time: 4.198 secs

Failed to install 'cordova-plugin-android-fingerprint-auth':Error: /pathToApp/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/pathToApp/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)


Error: /pathToApp/platforms/android/gradlew: Command failed with exit code 1
```

**Comment by mounir1** [comment] 2017-02-12 19:14
I had similar problem! I deleted node_modules files and reinstalled ionic and cordova from scratch 
$ cd /usr/local/lib/node_modules/  rm -rf *
$ brew install node
and problem solved .

**Comment by xdezinho** [comment] 2017-03-21 20:34
Make sure the names of installed plugins are the same as the "Cordova Plugins" site

I had the same problem with the call-number plugin
In the fetch.json file in ./plugins the name was different than it was to be
Example:
Previous =
```

"Mx.ferreyra.callnumber": {
         "Source": {
             "Type": "registry",
             "Id": "call-number"
         },
         "Is_top_level": true,
         "Variables": {}
     }
```

New =

```
"Call-number": {
         "Source": {
             "Type": "git",
             "Url": "https://github.com/Rohfosho/CordovaCallNumberPlugin.git",
             "Subdir": "."
         },
         "Is_top_level": true,
         "Variables": {}
     }
```
I solved by adding the plugin directly through the git url
Example:
Cordova plugin add https://github.com/Rohfosho/CordovaCallNumberPlugin.git

**Comment by leandrogehlen** [comment] 2017-04-04 23:33
I think that i found the problem.

To me, when it was necessary to update the ionic version, this error started to happens

To solve the problem i changed the `config.xml` for configurations compatible with latest version

**Comment by rajatkhare619** [comment] 2017-04-19 11:29
Running _sudo_ ionic state reset fixed it for me on Mac.

**Comment by nebulr** [comment] 2017-06-26 15:24
@rajatkhare619 this fixed it must be a permissions issue somewhere. However shouldn't need to call sudo ..

**Closed** 2017-07-10 22:32 UTC

**Comment by jhlee8804** [comment] 2017-11-24 02:59
See `npm-debug.log` file in project folder.
