### ISSUE TITLE
Plugin removal

### ISSUE THREAD

**Issue by leonardosalles** [ionic-team/ionic-cli#2841] opened 2017-10-26 17:47 UTC
**Description:**

Ionic is not removing references for a plugin in android.json and fetch.json files inside plugins folder. 

**Steps to Reproduce:**

install a cordova plugin and remove that plugin, if you check plugins/android.json the plugin reference will still there.

Example repo: 

1.
2.
3.

**Output:**

**My `ionic info`:**

cli packages: (C:\sabemi-digital\node_modules)
@ionic/cli-utils : 1.15.0
ionic (Ionic CLI) : 3.15.0
global packages:
cordova (Cordova CLI) : 7.0.1
local packages:
@ionic/app-scripts : 3.0.0
Cordova Platforms : android 6.2.3 browser 4.1.0
Ionic Framework : ionic-angular 3.7.1
System:
Node : v6.11.3
npm : 3.10.10
OS : Windows 8.1
Environment Variables:
ANDROID_HOME : not set
Misc:
backend : legacy

**Other Information:**

**Comment by dwieeb** [comment] 2017-10-26 20:38
Does the same thing happen using just the Cordova CLI? 

`cordova plugin add x`
`cordova plugin rm x`

**Comment by leonardosalles** [comment] 2017-10-29 19:08
Yes, same happening with cordova command.

**Comment by dwieeb** [comment] 2017-10-30 15:11
I'm not able to reproduce on Cordova CLI 7.0.1. 

Can you show the output of the commands? Is there an error? Is this breaking something for you?

**Comment by leonardosalles** [comment] 2017-10-30 19:08
No errors, plugin are removed but it does not remove the keys at my package.json and it infers my build because my app try to reinstall the plugin or try to include it on build and fails because does not find the plugin.

**Comment by jcesarmobile** [comment] 2022-05-06 14:44
it was a cordova bug and I can't reproduce with latest CLI version, so it's probably fixed by now
ionic cordova command just forwards the command to cordova CLI

**Closed by jcesarmobile** 2022-05-06 14:44 UTC
