### ISSUE TITLE
angular 9 cli livereload -l cause cordova_not_available cordova.js not injected

### ISSUE THREAD

**Issue by mohamedsharaf** [ionic-team/ionic-cli#4313] opened 2020-02-08 18:24 UTC
**Description:**

angular 9 cli livereload -l cause cordova_not_available cordova.js not injected

**Steps to Reproduce:**

ionic cordova run ios -l --target= device_identifier

**Output:**

**My `ionic info`:**

```

Ionic:

   Ionic CLI                     : 5.4.16 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.900.1
   @angular-devkit/schematics    : 9.0.1
   @angular/cli                  : 9.0.1
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 50 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/mohamed/Library/Android/sdk/)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v12.11.1 (/usr/local/Cellar/node/12.11.1/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 11.3.1 Build version 11C504

```

**Other Information:**

i am sure its cli becaue if i downgrade to angular8 every thing works fine

**Comment by liamdebeasi** [comment] 2020-02-11 14:55
Can you try this with Ionic 5? (`npm i @ionic/angular@next`). Ionic 4 does not support Angular 9.

**Comment by mohamedsharaf** [comment] 2020-02-11 21:32
i can confirm its still exist inn ionic 5.0.0 with angula 9.0.0 same problem here is a public repo so u can test
https://github.com/mohamedsharaf/i5ng9
run
ionic cordova run ios -l

**Comment by liamdebeasi** [comment] 2020-02-12 13:56
Closing as a duplicate of https://github.com/ionic-team/ionic/issues/20450. Please do not open the same issue across multiple repos.

**Closed by liamdebeasi** 2020-02-12 13:56 UTC
Labels: triage
