### ISSUE TITLE
Breaking ionic serve doesn't close the connection

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic-cli#3401] opened 2018-07-26 09:54 UTC
**Description:**

Using `ionic serve --port=8101` and then breaking it (CTRL+C) won't close the connection.

**Steps to Reproduce:**

1. install latest ionic locally and globally
```
The Ionic CLI has an update available (3.20.0 => 4.0.1)! Would you like to install it? Yes
> npm i -g ionic@latest
✔ Running command - done!

[OK] Updated Ionic CLI to 4.0.1! 🎉

Please re-run your command.

Note: You can downgrade to your old version by running: npm i -g ionic@3.20.0
```
2. run `ionic serve --port=8101`
3. wait for it to finish building.
4. CTRL+C
5. run `ionic serve --port=8101`
6. you will see he started using port 8102 since 8101 is occuped
7. check ionic processes: `ps -ef | grep ionic`
8. You now have two entries from serve.

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.4

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v10.0.0 (/usr/local/Cellar/node/10.0.0/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/gregorpapez/Library/Android/sdk

```

**Comment by adailtonribeiro** [comment] 2018-07-26 15:29
I'm having the same issue since the version '4.0.0-rc.11'. The version '4.0.0-rc.10' works fine for me.
...
4.0.0-rc.9   <-- It doesn't work
**4.0.0-rc.10 <-- It works fine**
4.0.0-rc.11 <-- It doesn't work
...
4.0.1          <-- It doesn't work

My ionic info:

> Ionic:
> 
>    ionic (Ionic CLI)  : 4.0.1 (C:\Users\john\AppData\Roaming\npm\node_modules\ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.1.11
> 
> Cordova:
> 
>    cordova (Cordova CLI) : 8.0.0
>    Cordova Platforms     : android 7.1.1
> 
> System:
> 
>    Android SDK Tools : 26.1.1
>    NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
>    npm               : 5.6.0
>    OS                : Windows 10
> 
> Environment:
> 
>    ANDROID_HOME : C:\Users\john\AppData\Local\Android\Sdk

**Comment by dwieeb** [comment] 2018-07-26 18:43
I closed https://github.com/ionic-team/ionic-cli/issues/3022 in favor of this one, because it already has better repro steps, information, etc.

This is the first time I've seen it happen on a non-Windows machine @lordgreg FWIW, I've never seen this on my machine, but several people have reported it.

@lordgreg @adailtonribeiro Could you paste the output of `ps -ef | grep ionic` (or similar command for windows)? Is it the Ionic CLI that is not shutting down or is it the `ionic-app-scripts` process? 

@adailtonribeiro Interesting. I did change some things related to serve in [rc.10 -> rc.11](https://github.com/ionic-team/ionic-cli/compare/ionic@4.0.0-rc.10...ionic@4.0.0-rc.11). @lordgreg Would you mind installing those and seeing if you see the same thing?

My `ionic info`:

```
Ionic:

   ionic (Ionic CLI)  : 4.0.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.8

Cordova:

   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : android 6.2.3, ios 4.4.0

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (/Users/dan/.nvm/versions/node/v8.11.3/bin/node)
   npm               : 5.10.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/dan/Library/Android/sdk
```

**Comment by adailtonribeiro** [comment] 2018-07-26 23:05
@dwieeb  I didn't find a similar command for windows but I think the ionic-app-scripts is shutting down properly because when I run `npm run ionic:serve`(ionic-app-scripts serve) it works

Using ionic CLI 4.0.1 and project type 'ionic-angular' (v3)

`ionic serve` <-- it's **not** shutting down properly
`npm run ionic:serve` <-- it's shutting down properly

Also ionic CLI 4.0.1 is not shutting down for project type 'angular' (v4)

My `ionic info` for project type 'angular':

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (C:\Users\john\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.1
   @angular-devkit/schematics : 0.7.1
   @angular/cli               : 6.1.1
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

Environment:

   ANDROID_HOME : C:\Users\john\AppData\Local\Android\Sdk
```

**Comment by dwieeb** [comment] 2018-07-27 00:57
@adailtonribeiro Thanks! Would you mind pasting the last bit of output of `ionic serve --verbose`? I am looking for output after this line:

```
  ionic:cli-framework:utils:process onBeforeExit handler: SIGINT received
```

**Comment by dwieeb** [comment] 2018-07-27 01:06
@lordgreg If you send TERM signal to the process, is it killed?

Try `kill <pid>`

**Comment by lordgreg** [comment] 2018-07-27 06:21
@dwieeb Thank you, here's the info you requested:

1. After killing the process,
```
▶ ps -ef | grep ionic
  501  4100     1   0 11:58am ??         0:02.00 ionic
  501 18761     1   0  8:17am ttys001    0:23.25 node /Users/gregorpapez/Projects/aesculap/aesculap-ionic/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
  501 18888     1   0  8:17am ttys001    0:03.37 node /Users/XXXXXX/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8102 --livereload-port 35730 --dev-logger-port 53704 --nobrowser
  501 18890 18761   0  8:17am ttys001    0:00.86 /usr/local/Cellar/node/10.0.0/bin/node /Users/gregorpapez/Projects/aesculap/aesculap-ionic/node_modules/@ionic/app-scripts/dist/transpile-worker.js
  501 18965 18761   0  8:17am ttys001    0:02.58 /usr/local/Cellar/node/10.0.0/bin/node /Users/XXXXXX/node_modules/@ionic/app-scripts/dist/worker-process.js /usr/local/Cellar/node/10.0.0/bin/node /Users/XXXXXX/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser -- --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
  501 18969 12575   0  8:18am ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ionic
```

And, as you can see, its about the `ionic-app-scripts`, not `ionic`. 

One thing to take into the consideration, why am I taking another port? Because `8100` is taken from another process, unrelated to ionic.

Killing it, as you'we wrote, kills the process.
```
Projects/XXXX  master ✗                                                                                                                                                                                                           6m ⚑
▶ kill 18761

Projects/XXXX  master ✗                                                                                                                                                                                                           7m ⚑
▶ kill 18888

Projects/XXXX  master ✗                                                                                                                                                                                                           8m ⚑
▶ ps -ef | grep ionic
  501  4100     1   0 11:58am ??         0:02.00 ionic
  501 19337 12575   0  8:21am ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ionic

```

**Comment by lordgreg** [comment] 2018-07-27 06:22
@dwieeb Thank you, here's the info you requested:

1. After killing the process,
```
▶ ps -ef | grep ionic
  501  4100     1   0 11:58am ??         0:02.00 ionic
  501 18761     1   0  8:17am ttys001    0:23.25 node /Users/XXXXXX/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
  501 18888     1   0  8:17am ttys001    0:03.37 node /Users/XXXXXX/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8102 --livereload-port 35730 --dev-logger-port 53704 --nobrowser
  501 18890 18761   0  8:17am ttys001    0:00.86 /usr/local/Cellar/node/10.0.0/bin/node /Users/XXXXXX/node_modules/@ionic/app-scripts/dist/transpile-worker.js
  501 18965 18761   0  8:17am ttys001    0:02.58 /usr/local/Cellar/node/10.0.0/bin/node /Users/XXXXXX/node_modules/@ionic/app-scripts/dist/worker-process.js /usr/local/Cellar/node/10.0.0/bin/node /Users/XXXXXX/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser -- --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
  501 18969 12575   0  8:18am ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ionic
```

And, as you can see, its about the `ionic-app-scripts`, not `ionic`. 

One thing to take into the consideration, why am I taking another port? Because `8100` is taken from another process, unrelated to ionic.

Killing it, as you'we wrote, kills the process.
```
Projects/XXXX  master ✗                                                                                                                                                                                                           6m ⚑
▶ kill 18761

Projects/XXXX  master ✗                                                                                                                                                                                                           7m ⚑
▶ kill 18888

Projects/XXXX  master ✗                                                                                                                                                                                                           8m ⚑
▶ ps -ef | grep ionic
  501  4100     1   0 11:58am ??         0:02.00 ionic
  501 19337 12575   0  8:21am ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ionic
```

**Comment by adailtonribeiro** [comment] 2018-07-27 11:41
@dwieeb Running `ionic serve --verbose` using the **ionic CLI 4.0.1** doesn't show anything after pressing (Ctrl + C)

However, if I use the **ionic CLI 4.0.0-rc.10** after pressing (Ctrl + C) show those lines:

```
  ionic:cli-framework:utils:process onBeforeExit handler: SIGINT received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 queued functions +0ms
  ionic:cli-utils:lib:hooks Looking for ionic:serve:after npm script. +50s
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 0) +16ms
```

**Comment by dwieeb** [comment] 2018-07-27 18:49
@lordgreg Do you see "SIGINT received" in the verbose output?

I have found if the `ionic` process is killed forcefully (e.g. `kill -9 <pid>`), the `ionic-app-scripts` process continues running because the parent process doesn't have time to clean up its resources. If the CLI gets the chance to, it uses [`p.kill()`](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_subprocess_kill_signal), which is the same as `kill <pid>` (both `TERM` signal).

@lordgreg What is the output of `stty -a`?

@adailtonribeiro On Windows it's a bit different, I'm not exactly sure how NodeJS maps these signals. That's helpful, though. Do you see `Environment closed.` in the verbose output, at least?

**Comment by janpio** [comment] 2018-07-30 09:42
Some more reports: https://forum.ionicframework.com/t/ionic-4-ionic-serve-port/136680

**Comment by lordgreg** [comment] 2018-07-31 06:26
@dwieeb sorry for the late response,

After running
```
ionic serve -b --port=8101 --verbose
```

Here's the result when breaking the script (CTRL+C):
```
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533018194833,"id":"763534","nspace":"devapp","name":"Faketitle Ionic@8101","host":"my-external-host-here","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +0ms
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533018196835,"id":"763534","nspace":"devapp","name":"Faketitle Ionic@8101","host":"my-external-host-here","ip":"11.21.4.213","port":8101,"commPort":53233,"path":"/"}' to 11.21.7.255 +2s
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533018196835,"id":"763534","nspace":"devapp","name":"Faketitle Ionic@8101","host":"my-external-host-here","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +1ms
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533018198837,"id":"763534","nspace":"devapp","name":"Faketitle Ionic@8101","host":"my-external-host-here","ip":"11.21.4.213","port":8101,"commPort":53233,"path":"/"}' to 11.21.7.255 +2s
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533018198837,"id":"763534","nspace":"devapp","name":"Faketitle Ionic@8101","host":"my-external-host-here","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +0ms

  ionic:cli-framework:utils:process onBeforeExit handler: SIGINT received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 queued functions +0ms
  ionic:cli-utils:lib:hooks Looking for ionic:serve:after npm script. +52s
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 0) +2ms
```

The `ps` output is the same, killable with `kill pid` command.

**Comment by dwieeb** [comment] 2018-07-31 16:28
Thank you @lordgreg 

@lordgreg @adailtonribeiro When you get a chance, please try this testing release to see if the issue is resolved:

```
npm i -g ionic@4.1.0-testing.b8379be8
```

**Comment by adailtonribeiro** [comment] 2018-07-31 17:47
@dwieeb I've tested the version `4.1.0-testing.b8379be8` using two projects (V3 and V4) and in either case, it didn't solve the issue for me.

also running `ionic serve --verbose` still doesn't show anything in the console after pressing (Ctrl + C), not even `Environment closed`

My `ionic info` for **V3**:

```
Ionic:

   ionic (Ionic CLI)  : 4.1.0-testing.b8379be8 (C:\Users\john\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

My `ionic info` for **V4**:

```
Ionic:
   ionic (Ionic CLI)          : 4.1.0-testing.b8379be8 (C:\Users\john\AppData\Roaming\npm\node_modules\ionic)   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.1   @angular-devkit/schematics : 0.7.1
   @angular/cli               : 6.1.1   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1
Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v8.11.3 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10
```

**Comment by dwieeb** [comment] 2018-07-31 18:10
@adailtonribeiro Thank you for testing. I added some more debug statements that may print. Can you paste the last bit of output after you use Ctrl-C on `ionic serve --verbose`?

**Comment by lordgreg** [comment] 2018-08-01 07:57
@dwieeb Hi, I've updated both (global and local) versions to your hash.

Starting and cancelling the ionic serve:
```
ionic:discover:publisher Publisher starting +0ms

[INFO] Development server running!

       Local: http://localhost:8101
       External: http://10.21.4.213:8101, http://192.168.56.1:8101
       DevApp: Aesculap Ionic@8101 on gpapez.mwaysolutions.com

       Use Ctrl+C to quit this process

  ionic:cli-utils:lib:events No process.send, not emitting event serve:ready +0ms
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110024269,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"10.21.4.213","port":8101,"commPort":53233,"path":"/"}' to 10.21.7.255 +2s
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110024270,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +0ms
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110026274,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"10.21.4.213","port":8101,"commPort":53233,"path":"/"}' to 10.21.7.255 +2s
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110026274,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +0ms
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110028278,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"10.21.4.213","port":8101,"commPort":53233,"path":"/"}' to 10.21.7.255 +2s
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110028278,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +0ms
[npm] [09:53:49]  webpack finished in 11.45 s
[npm] [09:53:49]  sass started ...
[npm] Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110030282,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"10.21.4.213","port":8101,"commPort":53233,"path":"/"}' to 10.21.7.255 +2s
  ionic:discover:publisher Broadcasting 'ION_DP{"t":1533110030282,"id":"862794","nspace":"devapp","name":"Aesculap Ionic@8101","host":"gpapez.mwaysolutions.com","ip":"192.168.56.1","port":8101,"commPort":53233,"path":"/"}' to 192.168.56.255 +0ms

  ionic:cli-framework:utils:process onBeforeExit handler: SIGINT received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 queued functions +0ms
  ionic:cli-utils:lib:hooks Looking for ionic:serve:after npm script. +25s
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 0) +2ms
```

`ps -ef | grep ionic`
```
  501 74186 74185   0  9:53AM ttys000    0:00.01 sh -c npm run mway env-set local && ionic-app-scripts serve "--address" "0.0.0.0" "--port" "8101" "--livereload-port" "35729" "--dev-logger-port" "53703" "--nobrowser"
  501 74195 74186   0  9:53AM ttys000    0:27.58 node /Users/user/Projects/abc/xxxxx-ionic/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8101 --livereload-port 35729 --dev-logger-port 53703 --nobrowser
  501 74544 74543   0  9:54AM ttys000    0:00.01 sh -c npm run mway env-set local && ionic-app-scripts serve "--address" "0.0.0.0" "--port" "8102" "--livereload-port" "35730" "--dev-logger-port" "53704" "--nobrowser"
  501 74554 74544   0  9:54AM ttys000    0:25.36 node /Users/user/Projects/abc/xxxxx-ionic/node_modules/.bin/ionic-app-scripts serve --address 0.0.0.0 --port 8102 --livereload-port 35730 --dev-logger-port 53704 --nobrowser
  501 74557 74195   0  9:54AM ttys000    0:01.03 /usr/local/Cellar/node/10.0.0/bin/node /Users/user/Projects/abc/xxxxx-ionic/node_modules/@ionic/app-scripts/dist/transpile-worker.js
  501 74749 54514   0  9:56AM ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ionic

```

Sadly, it didn't helped.

**Comment by dwieeb** [comment] 2018-08-01 17:26
They didn't print either 😞 

I will cut a testing release using [`tree-kill`](https://www.npmjs.com/package/tree-kill) and see if that works. Stay tuned.

**Comment by dwieeb** [comment] 2018-08-02 15:21
@lordgreg @adailtonribeiro Please try this testing release using `tree-kill`:

```
npm i -g ionic@4.1.0-testing.fabaebf2
```

**Comment by adailtonribeiro** [comment] 2018-08-02 20:08
@dwieeb Unfortunately it didn't solve the issue for me

Also, I ran `ionic serve --verbose` but there was no output after pressing Ctrl+C

**Comment by dwieeb** [comment] 2018-08-03 00:13
@adailtonribeiro Yeah... your computer doesn't appear to give the Ionic CLI time to shutdown and clean up its resources. This debug line should print if the shutdown is handled gracefully:

```
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 queued functions +0ms
```

Is your terminal sending `SIGKILL` for some reason? What terminal are you using?

**Comment by dwieeb** [comment] 2018-08-03 00:49
@adailtonribeiro Very strange, but my Windows machine does NOT work with `ionic@4.1.0-testing.fabaebf2` (using `tree-kill`) but DOES work with `ionic@4.0.3` (using `p.kill()`).

I also don't see the debug logs I was expecting with Ctrl+C, but I DO see them with Ctrl+Break (read more: https://docs.microsoft.com/en-us/windows/console/ctrl-c-and-ctrl-break-signals)

Windows is tough...

**Comment by dwieeb** [comment] 2018-08-03 01:25
@adailtonribeiro Sorry for the tag spam. One more thing to try: on 4.0.3, try running this instead:

```
ionic serve --verbose --no-interactive
```

**Comment by lordgreg** [comment] 2018-08-03 06:14
Good morning @dwieeb and others :)

I've updated BOTH, global and local ionic to your `faaebf2` version.
```
▶ ionic serve -b --port=8101 --verbose
  ...
  ... >>>>> CTRL+C pressed 

  ionic:cli-framework:utils:process onBeforeExit handler: SIGINT received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 2 queued functions +0ms
  ionic:cli-utils:lib:hooks Looking for ionic:serve:after npm script. +57s
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 0) +101ms
```

```
▶ ps -ef | grep ionic                  
  501  7294 58663   0  8:11AM ttys004    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ionic
```

Hey! No port left behind! I think you've did it @dwieeb 🚀 


This issue is now (as it seems) fixed on Mac! (I cannot say the same with @adailtonribeiro  is having). I will, however, also try to update my Windows machine with latest version and report the status.

**Comment by Marineau** [comment] 2018-08-03 09:12
Got the same problem and it's now keeping me from coding anything since I can't even kill it manually in the task manager, it doesnt appear everytime in the list but still running in background, don't know where !
So we're saying Ionic is currently full K.O. or is there any turn around, something ?

**Comment by dwieeb** [comment] 2018-08-03 19:05
@adailtonribeiro I see. It seems the issue is related to what a dependency is doing with process events and signals. 

@lordgreg Awesome. I believe `tree-kill` is becoming the cross-platform standard. (it's used by webpack and Angular CLI).

Please follow https://github.com/ionic-team/ionic-cli/pull/3481 for the fix. It will be a combination of using `tree-kill` and some hacks that I don't know how to do yet. Thank you so much for testing @adailtonribeiro and @lordgreg!

**Comment by dwieeb** [comment] 2018-08-08 17:03
@adailtonribeiro Is this still broken for you in 4.0.5?

**Comment by adailtonribeiro** [comment] 2018-08-08 19:06
@dwieeb yes, it was fixed in 4.0.4 but sadly it's broken again in 4.0.5

**Comment by dwieeb** [comment] 2018-08-08 22:41
@adailtonribeiro The issue is kind of an architecture problem. I hopefully addressed it in https://github.com/ionic-team/ionic-cli/pull/3500

I tested on my Windows machine and it seems to work, but if you have a moment please try:

```
npm i -g ionic@4.1.0-testing.6a88cfe2
```

**Comment by adailtonribeiro** [comment] 2018-08-09 00:36
@dwieeb I tested on my machine and it's working for me too
Thank you so much for that!

**Closed** 2018-08-09 14:38 UTC
Labels: bug, project type: ionic-angular

**Comment by w3-jostergaard** [comment] 2020-10-22 14:07
Hey together, I know this issue is old, but I got the exact problem with ionic -v 5.4.16

For me, even when I use `ionic cordova run android --device` a node process keep staying alive, I noticed it when my CPU usage got very high from several instances of node.js.

I use Windows 10 Home Version (10.0.19042 Build 19042)

`ionic info` also freezes the cli with `ionic info --verbose` i get following output before it freezes:

`ionic:lib Terminal info: { ci: false, shell: 'C:\\WINDOWS\\system32\\cmd.exe', tty: true, windows: true } +0ms`

`ionic:lib CLI global options: { _: [ 'info' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: 
null, json: null, project: null, '--': [] } +5ms`

`ionic:lib:project Project type from config: Ionic 2/3 (ionic-angular) +0ms`

`ionic:lib:project Project details: { configPath: 'C:\\dev\\angular_projects\\panthera-automotive-app\\ionic.config.json', errors: [], context: 'app', type: 'ionic-angular' } +1ms`

`ionic Context: { binPath: 'C:\\Users\\Jonas Ostergaard\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\Jonas Ostergaard\\AppData\\Roaming\\npm\\node_modules\\ionic', execPath: 'C:\\dev\\angular_projects\\panthera-automotive-app', version: '5.4.16' } +0ms`

`ionic:lib:telemetry Sending telemetry for command: 'ionic info' [ '--verbose', '--interactive', '--color' ] +0ms`

Does someone has an idea? Got the problem reintroduced in a newer version?
