### ISSUE TITLE
After upgrade to v4, iOS status bar padding in ionic lab is missing

### ISSUE THREAD

**Issue by bnfrnz** [ionic-team/ionic-cli#3657] opened 2018-10-02 03:50 UTC
**Description:**

Ever since I upgraded from ionic cli 3 to 4, the iOS status bar padding in ionic lab has disappeared. When building cordova, on a device everything's fine. It seems to just be a lab issue.

**Steps to Reproduce:**

`ionic lab`

**Output:**

Status bar (battery percentage etc.) overlap ion-header.

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)  : 4.1.2 
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 14 other plugins)

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 2.0.0
   ios-sim           : 7.0.0
   NodeJS            : v8.12.0
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Comment by dwieeb** [comment] 2018-10-02 16:31
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3069

**Comment by dwieeb** [comment] 2018-10-02 16:32
Unfortunately this is still not fixed.

**Closed by dwieeb** 2018-10-02 16:32 UTC
Labels: triage
