### ISSUE TITLE
Ionic lab does not render IOS UI

### ISSUE THREAD

**Issue by TylerBurnett** [ionic-team/ionic-cli#4575] opened 2020-10-01 05:51 UTC
**Description:**

When using Ionic lab I find that the UI between the two rendered frames (IOS,MD) are exactly the same and do not differ. it appears that Ionic lab only renders MD components in the lab.

![image](https://user-images.githubusercontent.com/11090043/94772650-70434c80-03fd-11eb-8df1-9d896b81d135.png)

**Steps to Reproduce:**

Open ionic lab with any app.

**Output:**

ionic serve -l
ionic serve --lab

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.11.10 (C:\Users\Tyler\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.1.0

Capacitor:

   Capacitor CLI   : 2.1.0
   @capacitor/core : 2.4.1

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v12.18.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.6
   OS     : Windows 10
```

**Other Information:**

- Upgrading to @ionic/lab@3.2.0 or higher does not fix the issue. Instead, it creates a 404 error and doesn't render the lab at all
- Specific components can be forced into rendering in IOS by using the mode attribute on the specific component (but it can create oversizing issues)
![image](https://user-images.githubusercontent.com/11090043/94772813-cc0dd580-03fd-11eb-90c8-e59fbdea907e.png)

**Comment by Flusinerd** [comment] 2020-10-11 21:04
Hello, I can confirm this.
For me its not working, after saving something in my project and live reload triggering.
If I manually refresh ionic-lab then it works as intended.

Using latest Google Chrome

**Comment by franknoel** [comment] 2021-08-04 16:02
I'm having the same issue and I'm not able to fix it with live reload or restarting the process.

Ionic CLI: 6.16.3
Ionic Framework: @ionic/react 5.6.12
Ionic lab: 3.2.10
Capacitor: 3.1.2
OS: Catalina
NodeJS: 14.15.3
Browser: Google Chrome

**Comment by SaroGFX** [comment] 2022-08-11 11:47
I have the same on Safari and Chrome 

Also the safe areas are not respected in lab, maybe using an iphone without a notch can help also to not have this visual glitch. 

<img width="901" alt="Screenshot 2022-08-11 at 13 47 37" src="https://user-images.githubusercontent.com/3781800/184126656-47b0b2c2-536e-4b9d-8d9d-fd86848a7e8c.png">

**Comment by liamdebeasi** [comment] 2023-01-09 14:24
Hi everyone,

We recently deprecated Ionic Labs in favor of using the built-in browser tools for mobile emulation. These tools more accurately simulate a mobile environment than Ionic Labs does. We have documentation for getting set up with the browser dev tools on our documentation website: https://ionicframework.com/docs/developing/previewing

I am going to close this, but let me know if there are any questions.

**Closed as not planned by liamdebeasi** 2023-01-09 14:24 UTC
Labels: triage
