### ISSUE TITLE
`ionic info`: Duplicate output of "Ionic Framework" 

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-cli#2240] opened 2017-05-10 09:34 UTC
From the forum:

```
Ionic Framework                 : ionic-angular 3.1.0
Ionic Framework                 : unknown
```

https://forum.ionicframework.com/t/cannot-install-inappbrowser-plugin-after-ionic-cli-v3-installed/89636

**ionic info**

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0
    Ionic CLI        : 3.0.0

local packages:

    @ionic/app-scripts              : 1.3.5
    @ionic/cli-plugin-cordova       : 1.0.0
    @ionic/cli-plugin-ionic-angular : 1.0.0
    @ionic/cli-plugin-ionic1        : 1.0.0
    Ionic Framework                 : ionic-angular 3.1.0
    Ionic Framework                 : unknown

System:

    Node       : v7.9.0
    OS         : Windows 8
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment] 2017-05-10 17:12
It prints twice because that information comes from the plugins, and both project plugins are installed.

```
@ionic/cli-plugin-ionic-angular : 1.0.0
@ionic/cli-plugin-ionic1        : 1.0.0
```

I can try to print warnings about this.

**Comment by piotrowski** [comment] 2017-05-10 17:21
Ha - interesting that this doesn't explode ;)

**Comment by dwieeb** [comment] 2017-07-13 22:20
This issue became a dupe of https://github.com/ionic-team/ionic-cli/issues/2401

**Closed by dwieeb** 2017-07-13 22:20 UTC
