### ISSUE TITLE
"ionic serve" command does not work in Windows environment 

### ISSUE THREAD

**Issue by festusmwambu** [ionic-team/ionic-cli#4884] opened 2022-07-04 12:11 UTC
- I am having an error running the simple command of **ionic serve** natively in Windows using Git Bash. This is the error I get:

    $ ionic serve
    > ng.cmd run app:serve --host=localhost --port=8100
    [ng] Error: Schema validation failed with the following errors:
    [ng]   Data path "" must NOT have additional properties(es5BrowserSupport).
    
    [ERROR] ng has unexpectedly closed (exit code 1).
    
            The Ionic CLI will exit. Please check any output above for error details.

- This is the solution that I found and I thought it was good to share:
    On *angular.json* file if you have an empty "scripts": [] and "es5BrowserSupport": true , just remove it ! and then run _ionic serve_
    
    ```
     "build": {
          "options": {
           ...,
            "scripts": [],                <-- Remove this line
            "es5BrowserSupport": true     <-- Remove this line
           ...

**Comment by jcesarmobile** [comment] 2022-07-05 17:35
duplicate of https://github.com/ionic-team/ionic-cli/issues/4883

**Closed as not planned by jcesarmobile** 2022-07-05 17:35 UTC
Labels: triage
