### ISSUE TITLE
ionic serve --ssl does not serve via https

### ISSUE THREAD

**Issue by mharrisn** [ionic-team/ionic-cli#3432] opened 2018-07-29 15:40 UTC
**Description:**

Neither `ionic serve --ssl` or `ionic serve -s` appear to have any effect. As a result, I cannot serve with https, which restricts capabilities like geolocation in most modern browsers.

According to this commit, it was included: https://github.com/ionic-team/ionic-cli/commit/ed14f58454cb0ed8d84a2b52a566da400eea40ec

**Steps to Reproduce:**

Create a new Ionic 4 project
Run `ionic serve --ssl`

**Output:**

`ng run app:serve --host=0.0.0.0 --port=8101`
appears to be the resulting command

**My `ionic info`:**

```
Ionic:

   ionic (Ionic CLI)          : 4.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.0
   @angular-devkit/core       : 0.7.0-rc.3
   @angular-devkit/schematics : 0.7.0-rc.3
   @angular/cli               : 6.0.8
   @ionic/ng-toolkit          : 1.0.0
   @ionic/schematics-angular  : 1.0.1

System:

   NodeJS : v9.4.0 (/usr/local/Cellar/node/9.4.0/bin/node)
   npm    : 6.2.0
   OS     : macOS High Sierra
```

**Other Information:**

**Comment by dwieeb** [comment] 2018-07-30 15:33
Thanks for the issue!

The changelog at time of release is here: https://github.com/ionic-team/ionic-cli/blob/08dba217e3c091b197593fdd6a57cb360b68183a/packages/ionic/CHANGELOG.md

This is already being tracked here: https://github.com/ionic-team/ionic-cli/issues/3305

**Comment by dwieeb** [comment] 2018-07-30 15:33
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3305

**Closed by dwieeb** 2018-07-30 15:33 UTC
Labels: triage
