### ISSUE TITLE
Failed to build with plugin from URL

### ISSUE THREAD

**Issue by alecsam** [ionic-team/ionic-cli#3701] opened 2018-10-22 13:47 UTC
**Decription:**
After installing the latest head version of _cordova-plugin-background-mode_, build for Android fails. However, if I run the build command without first deleting _node_modules_, _platforms_ and _plugins_, the build works just fine.

In config.xml:
```
<plugin name="cordova-plugin-background-mode" spec="https://github.com/katzer/cordova-plugin-background-mode.git" />
```
In package.json:
```
"dependencies": {
"cordova-plugin-background-mode": "git+https://github.com/katzer/cordova-plugin-background-mode.git"
}
```
In package-lock.json:
```
"cordova-plugin-background-mode": {
      "version": "git+https://github.com/katzer/cordova-plugin-background-mode.git#a2352f5d8b17de5799b35177d9c7c4f32f66c49e"
```

**Steps to reproduce:**
1. cordova plugin add https://github.com/katzer/cordova-plugin-background-mode.git
2. delete node_modules, platforms and plugins (as if I want to simulate a fresh restore)
2. ionic cordova build android

**Output:**
```
Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependencies? Yes
Installing dependencies may take several minutes!
> npm i
× Running command - failed!
[ERROR] An error occurred while running npm i (exit code 1):

        npm ERR! code 128
        npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
        npm ERR! fatal: 'submodule' appears to be a git command, but we were not
        npm ERR! able to execute it. Maybe git-submodule is broken?
        npm ERR!
```

**Ionic info:**
cli packages: (C:\Users\a\AppData\Roaming\npm\node_modules)
```
@ionic/cli-utils  : 1.19.2
ionic (Ionic CLI) : 3.20.0
```
global packages:
```
cordova (Cordova CLI) : 8.0.0
Gulp CLI              : CLI version 3.9.1 Local version 3.9.1
```
local packages:
```
@ionic/app-scripts : 3.1.10
Cordova Platforms  : android 7.0.0
Ionic Framework    : ionic-angular 3.9.2
```
System:
```
Android SDK Tools : 26.1.1
Node              : v8.11.3
npm               : 5.6.0
OS                : Windows 10
```

**Comment by dwieeb** [comment] 2018-10-22 17:52
Duplicate of https://github.com/ionic-team/ionic-cli/issues/2716

**Closed by dwieeb** 2018-10-22 17:52 UTC

**Comment by alecsam** [comment] 2018-10-23 06:49
Before posting my problem, I've read #2716 and I've tried every solution. For me none of them worked...

**Comment by dwieeb** [comment] 2018-10-23 15:44
@alecsam It's an unsolved issue. That's why the other issue is still open.
