### ISSUE TITLE
generate component : TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bleuscyther** [ionic-team/ionic-cli#2389] opened 2017-06-03 23:44 UTC
Ionic CLI generates an error

`ionic generate component foo `
TypeError: Cannot read property 'length' of undefined

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : none
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by dwieeb** [comment] 2017-06-05 23:42
Thanks, this is a duplicate of https://github.com/ionic-team/ionic-cli/issues/2389

**Closed by dwieeb** 2017-06-05 23:42 UTC

**Comment by bleuscyther** [comment] 2017-06-07 16:09
@dwieeb this is #2389, is there another ticket on that already?

**Comment by dwieeb** [comment] 2017-06-07 18:05
Haha, sorry. I meant https://github.com/ionic-team/ionic-cli/issues/2386

**Comment by arumuganainar73** [comment] 2017-09-01 16:41
Error: Cannot read property ‘length’ of undefined
ANDROID_HOME=C:\Users…\AppData\Local\Android\sdk1
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_121
Error: Cannot read property ‘length’ of undefined

[ERROR] An error occurred while running cordova run android (exit code 1).
how can i fix this? please help me
E:…>ionic info
[WARN] Error with .\www\lib\ionic\version.json file: FILE_NOT_FOUND, trying .\bower.json.

cli packages: (E:…\node_modules)

@ionic/cli-utils  : 1.9.2
ionic (Ionic CLI) : 3.9.2
global packages:

Cordova CLI : 7.0.1
local packages:

Cordova Platforms : android 6.2.3 ios 4.4.0
Ionic Framework   : ionic1 1.3.1
System:

Android SDK Tools : 25.2.5
Node              : v6.11.2
npm               : 5.3.0
OS                : Windows 10

**Comment by ahmad3ttallah** [comment] 2018-02-16 14:35
@arumuganainar73 Did you manage to fix that issue ?
