### ISSUE TITLE
Unable to disable lint during Cordova builds

### ISSUE THREAD

**Issue by soumak77** [ionic-team/ionic-cli#2491] opened 2017-07-03 03:14 UTC
**Description:**
Unable to disable lint during Cordova builds.  The `enableLint` command line option for ionic-app-scripts works when running `ionic serve`, but does not work when running `ionic cordova build`

**Steps to Reproduce:**
Example repo: N/A

1. Run command `ionic serve --enableLint false`
2. Observe log line
    - `[INFO] Starting app-scripts server: --enableLint false --port 8100 --p 8100 --livereload-port 35729 --r 35729 --address 0.0.0.0`
3. Run command `ionic cordova build browser --enableLint false`
4. Observe log line
    - `Running app-scripts build: --iscordovaserve --externalIpRequired --nobrowser`

**Output:**
Running the first command correctly passes the parameter to ionic-app-scripts and disables the linter.  Running the second command does not pass the parameter to ionic-app-scripts and therefore the linter is NOT disabled.

**My `ionic info`:**

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : browser 4.1.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.9.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.2.1 Build version 8C1002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 5.0.4 

**Other Information:**

**Comment by francoro** [comment] 2017-09-06 15:39
ionic cordova run android --device -lc --enablelint false

It doesnt desactivate the lint

**Comment by francoro** [comment] 2017-09-06 15:41
ionic cordova run android --device -lc --enableLint false

it doesnt desactivate the lint

**Comment by dwieeb** [comment] 2017-09-06 21:46
Whoops sorry, I missed this until that recent comment was posted. I will look into this soon.

**Comment by AbhayShiro** [comment] 2017-12-12 14:30
Most of the times it is caused by the plugins that are installed with the IDE. Kindly check your IDE plugins

**Comment by dwieeb** [comment] 2018-01-23 00:12
🔖 Update for 2018: `--enableLint` is still not being passed to `@ionic/app-scripts`. There's a whitelist of command options that are forwarded to app-scripts, but `--enableLint` is not one of them.

**Comment by Notifium** [comment] 2018-02-03 20:45
I'm seeing this as well.

**Comment by srjovanovic** [comment] 2018-03-28 22:19
Solution?

**Comment by dwieeb** [comment] 2018-03-29 00:12
app-scripts has a bunch of methods of configuration: https://github.com/ionic-team/ionic-app-scripts#overriding-config-values

You can set the option in `package.json` if it's a blocker for you.

**Comment by brownoxford** [comment] 2019-09-22 22:47
This appears to have been addressed since the initial report - I can no longer reproduce with Ionic CLI 5.4.1

**Comment by dwieeb** [comment] 2019-09-30 15:53
@brownoxford Are you using Ionic 3?

**Comment by brownoxford** [comment] 2019-10-01 16:49
> @brownoxford Are you using Ionic 3?

Yes, I'm on ionic 3

```
Ionic:

   Ionic CLI          : 5.4.1 (/Users/cabernet/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.8
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic 5.4.4, cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 12 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.8 

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/cabernet/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.11.3
   OS         : macOS Mojave
   Xcode      : Xcode 11.0 Build version 11A420a
```

**Comment by dwieeb** [comment] 2019-10-01 18:09
Interesting. I'm going to close this. If it's working, then great! 🎉 

If not, here's a workaround by @Guchster 👉 https://github.com/ionic-team/ionic-cli/issues/2491#issuecomment-389012015

**Closed by dwieeb** 2019-10-01 18:09 UTC
Labels: effort: low, enhancement, help wanted, project type: ionic-angular
