### ISSUE TITLE
Create Ionic project from Angular app

### ISSUE THREAD

**Issue by andreas-aeschlimann** [ionic-team/ionic-cli#3583] opened 2018-09-14 13:37 UTC
As Ionic (4) app seem to be even more similar to an Angular (6) app structure, would it be possible to integrate a project "transformer" command into the Ionic CLI?

I imagine it could be very helpful if one could generate an Ionic project just through a command that uses the source of an Angular app.

**Comment by dwieeb** [comment] 2018-09-14 15:52
Yeah, this is the `ng add` stuff.

**Comment by dwieeb** [comment] 2018-09-14 15:52
Duplicate of https://github.com/ionic-team/ionic-cli/issues/3369

**Closed by dwieeb** 2018-09-14 15:52 UTC
Labels: triage

**Comment by andreas-aeschlimann** [comment] 2018-09-18 11:46
Great, thank you!
