### ISSUE TITLE
Save to resources folder `www/svg` only used icons

### ISSUE THREAD

**Issue by VIMHaos** [ionic-team/ionic-cli#4097] opened 2019-07-22 13:31 UTC
In SVG folder save all icons, it's 696 files and 700 KB used.
In some apps uses only 5-15% of all icons, and it's can save about 500KB of application ..

**Comment by dwieeb** [comment] 2019-07-22 16:38
Duplicate of https://github.com/ionic-team/ionicons/issues/637

**Closed by dwieeb** 2019-07-22 16:38 UTC
Labels: triage
